// med_work_frontend/src/pages/Assistant/index.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Bubble, Sender } from '@ant-design/x';
import { XMarkdown } from '@ant-design/x-markdown';
import type { GetProp } from 'antd';
import { Button, App as AntApp, Avatar, Tag, Typography, Dropdown } from 'antd';
import {
  UserOutlined,
  LoadingOutlined,
  FileTextOutlined,
  DownloadOutlined,
  ArrowRightOutlined,
  BulbOutlined,
  SendOutlined,
  PaperClipOutlined,
  DownOutlined,
} from '@ant-design/icons';
import { colors } from '@/theme';
import assistantAvatar from '@/assets/assistant.png';
import {
  streamChat,
  getConversation,
  updateConversation,
  type ChatMessageInput,
} from '@/services/chat';
import { getAiConnections } from '@/services/api';
import type { AIConnectionResponse } from '@/types';
import { downloadDocumentFile, uploadDocumentApi } from '@/services/knowledge';
import { usePermission } from '@/utils/access';
import { useXChat, type XAgent, type XMessage } from '@/hooks/useXChat';
import { toPersist } from '@/hooks/chatMessageState';
import { useConversationStore } from '@/stores/conversations';
import {
  DataAnalysisIcon,
  KnowledgeSearchIcon,
  MedicalQuestionIcon,
  RecordAnalysisIcon,
} from './CapabilityIcons';
import './index.css';

const genId = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 7);

/** 模型胶囊左侧圆点的取色盘，按 provider 顺序轮转分配 */
const MODEL_DOT_COLORS = ['#7c4dff', '#2d6cdf', '#0b8f7f', '#c56a1a', '#d6455d'];

/** 聊天输入框可上传的文档类型（与后端 knowledge 上传接口白名单保持一致） */
const UPLOAD_ACCEPT = '.pdf,.docx,.txt,.md';

const CAPABILITIES = [
  {
    key: 'knowledge',
    title: '医学知识问答',
    description: '疾病诊疗、药品说明与临床指南查询',
    prompt: '高血压患者常见的用药注意事项有哪些？',
    icon: <MedicalQuestionIcon />,
  },
  {
    key: 'record',
    title: '病历智能分析',
    description: '梳理病历内容，辅助识别关键信息',
    prompt: '请分析这份病历并给出可能的诊断方向',
    icon: <RecordAnalysisIcon />,
  },
  {
    key: 'retrieval',
    title: '知识库检索',
    description: '检索本机构资料与医学知识库',
    prompt: '查询阿司匹林与华法林的相互作用',
    icon: <KnowledgeSearchIcon />,
  },
  {
    key: 'data',
    title: '数据分析',
    description: '归纳指标变化，提炼可读结论',
    prompt: '帮我总结最新的临床指标要点',
    icon: <DataAnalysisIcon />,
  },
] as const;

/** 助手消息下方的知识库引用卡片列表（含命中片段与原文下载） */
function CitationList({ citations }: { citations: NonNullable<XMessage['citations']> }) {
  const { message } = AntApp.useApp();
  const [downloading, setDownloading] = useState<number | null>(null);

  const handleDownload = async (docId: number, title: string) => {
    setDownloading(docId);
    try {
      await downloadDocumentFile(docId, `${title.replace(/[《》]/g, '')}.pdf`);
      message.success(`已开始下载「${title}」`);
    } catch {
      // 错误提示已由 api.ts 全局处理
    } finally {
      setDownloading(null);
    }
  };

  return (
    <div style={{ marginTop: 10, display: 'flex', flexDirection: 'column', gap: 6 }}>
      <Typography.Text type="secondary" style={{ fontSize: 12 }}>
        知识库引用（{citations.length}）
      </Typography.Text>
      {citations.map((c) => (
        <div
          key={c.document_id}
          style={{
            border: `1px solid ${colors.border}`,
            borderRadius: 8,
            padding: '8px 10px',
            background: colors.bgSecondary,
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <FileTextOutlined style={{ color: colors.primary, flexShrink: 0 }} />
            <span style={{ fontSize: 13, fontWeight: 600, flex: 1, minWidth: 0 }}>{c.title}</span>
            <Tag color="purple" style={{ marginInlineEnd: 0 }}>
              {Math.round((c.score || 0) * 100)}%
            </Tag>
            <Button
              type="link"
              size="small"
              icon={<DownloadOutlined />}
              style={{ padding: '0 4px' }}
              loading={downloading === c.document_id}
              onClick={() => void handleDownload(c.document_id, c.title)}
            >
              原文
            </Button>
          </div>
          {c.snippet ? (
            <Typography.Paragraph
              type="secondary"
              style={{ margin: '6px 0 0', fontSize: 12 }}
              ellipsis={{ rows: 2, expandable: true, symbol: '展开' }}
            >
              {c.snippet}
            </Typography.Paragraph>
          ) : null}
        </div>
      ))}
    </div>
  );
}

const roles: GetProp<typeof Bubble.List, 'role'> = {
  user: { placement: 'end', avatar: <Avatar size={28} icon={<UserOutlined />} style={{ background: colors.primary }} /> },
  assistant: { placement: 'start', avatar: <Avatar size={28} src={assistantAvatar} /> },
};

/** 后端消息（ChatRole 可能含 system）转为页面消息（仅 user / assistant） */
const toXMessage = (m: ChatMessageInput): XMessage => ({
  id: genId(),
  role: m.role === 'user' ? 'user' : 'assistant',
  content: m.content,
  status: m.role === 'assistant' ? 'done' : undefined,
  citations: m.citations ?? undefined,
});

export default function Assistant() {
  const { message } = AntApp.useApp();
  const location = useLocation();
  const navigate = useNavigate();
  const handledRequest = useRef<string>();
  const conversations = useConversationStore((state) => state.conversations);
  const selectedConversationKey = useConversationStore((state) => state.activeKey);
  const loadConversations = useConversationStore((state) => state.loadConversations);
  const ensureDraft = useConversationStore((state) => state.ensureDraft);
  const selectConversation = useConversationStore((state) => state.selectConversation);
  const renameConversation = useConversationStore((state) => state.renameConversation);
  const [convInitialized, setConvInitialized] = useState(false);
  const [activeKey, setActiveKey] = useState('');
  const [input, setInput] = useState('');
  const [loadingConversationKey, setLoadingConversationKey] = useState('');
  const [loadErrorKey, setLoadErrorKey] = useState('');
  const [aiConnections, setAiConnections] = useState<AIConnectionResponse[]>([]);
  const [selectedModel, setSelectedModel] = useState<string | null>(null);
  const [uploadingFile, setUploadingFile] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const modelRef = useRef<string | null>(null);
  const storeRef = useRef<Record<string, XMessage[]>>({});
  const loadVersionRef = useRef(0);
  const saveQueueRef = useRef<Record<string, Promise<unknown>>>({});

  // 当前激活会话与列表的引用（供防抖保存闭包读取最新值）
  const activeKeyRef = useRef(activeKey);
  const conversationsRef = useRef(conversations);
  useEffect(() => {
    activeKeyRef.current = activeKey;
  }, [activeKey]);
  useEffect(() => {
    conversationsRef.current = conversations;
  }, [conversations]);

  // 自定义 agent：把对话转给后端 /api/chat/stream 流式转发
  const agent = useMemo<XAgent>(
    () => ({
      request: ({ messages }, cb) => {
        streamChat(
          messages.map((m) => ({ role: m.role, content: m.content })),
          {
            model: modelRef.current ?? undefined,
            signal: cb.signal,
            onChunk: cb.onUpdate,
            onCitations: cb.onCitations,
            onDone: cb.onSuccess,
            onError: cb.onError,
          },
        );
      },
    }),
    [],
  );

  // 拉取 AI 连接与可用模型，构造 (provider/model) 选项
  useEffect(() => {
    let alive = true;
    void getAiConnections()
      .then((items) => {
        if (!alive) return;
        const enabled = items.filter((item) => item.enabled && item.has_api_key && item.models?.length);
        setAiConnections(enabled);
        // 默认选中第一个启用 provider 的 active_model；用户后续可手动切换
        if (!selectedModel) {
          const firstActive = enabled[0]?.active_model ?? null;
          setSelectedModel(firstActive);
          modelRef.current = firstActive;
        }
      })
      .catch(() => {
        /* AI 连接拉取失败不影响主流程，模型下拉显示为空 */
      });
    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /** model → 展示用 provider 名与圆点颜色（下拉里同名模型只保留首次出现的 provider） */
  const modelMeta = useMemo(() => {
    const meta: Record<string, { provider: string; model: string; color: string }> = {};
    aiConnections.forEach((conn, index) => {
      const color = MODEL_DOT_COLORS[index % MODEL_DOT_COLORS.length];
      conn.models.forEach((model) => {
        if (!meta[model]) meta[model] = { provider: conn.name, model, color };
      });
    });
    return meta;
  }, [aiConnections]);

  const currentModel = selectedModel ? modelMeta[selectedModel] : undefined;

  const modelMenuItems = useMemo(
    () =>
      aiConnections.flatMap((conn) =>
        conn.models.map((model) => ({ key: model, label: `${conn.name} / ${model}` })),
      ),
    [aiConnections],
  );

  const { messages, onRequest, onCancel, setMessages, loading } = useXChat({ agent });

  // 把当前会话的消息同步进 store，支持多会话切换
  useEffect(() => {
    if (activeKey) storeRef.current[activeKey] = messages;
  }, [messages, activeKey]);

  /** 保存按会话串行执行，避免旧快照晚完成而覆盖新消息。 */
  const saveConversation = useCallback((key: string, snapshot: XMessage[]) => {
    const item = conversationsRef.current.find((conv) => conv.key === key);
    if (!item) return;
    const persisted = toPersist(snapshot);
    if (!persisted.length) return;
    const previous = saveQueueRef.current[key] ?? Promise.resolve();
    const pending = previous.catch(() => undefined).then(() =>
      updateConversation(Number(key), { title: item.label, messages: persisted }),
    );
    saveQueueRef.current[key] = pending;
    void pending.catch(() => message.warning('对话保存失败，请稍后重试'));
  }, [message]);

  /** 拉取并应用指定会话的消息；旧请求不能覆盖当前视图。 */
  const loadConversation = useCallback(async (convId: number) => {
    const key = String(convId);
    const version = ++loadVersionRef.current;
    setLoadingConversationKey(key);
    setLoadErrorKey('');
    try {
      const detail = await getConversation(convId);
      if (version !== loadVersionRef.current || activeKeyRef.current !== key) return;
      const msgs = detail.messages.map(toXMessage);
      storeRef.current[key] = msgs;
      setMessages(msgs);
    } catch {
      if (version !== loadVersionRef.current || activeKeyRef.current !== key) return;
      setLoadErrorKey(key);
      message.error('会话内容加载失败');
    } finally {
      if (version === loadVersionRef.current) setLoadingConversationKey('');
    }
  }, [setMessages, message]);

  // 挂载：加载会话列表；空列表或新会话入口复用同一个草稿创建流程。
  useEffect(() => {
    let alive = true;
    const initialRequest = Boolean(location.state?.newConversation);
    const requestedKey = location.state?.conversationKey as string | undefined;
    if (initialRequest || requestedKey) {
      handledRequest.current = location.key;
      navigate('/assistant', { replace: true, state: null });
    }
    (async () => {
      try {
        const items = await loadConversations();
        if (!alive) return;
        const target = initialRequest
          ? await ensureDraft()
          : items.find((item) => item.key === requestedKey)
            ?? items.find((item) => item.key === selectedConversationKey)
            ?? items[0]
            ?? await ensureDraft();
        if (!alive) return;
        setActiveKey(target.key);
        selectConversation(target.key);
        activeKeyRef.current = target.key;
        const detail = await getConversation(Number(target.key));
        if (!alive) return;
        storeRef.current[target.key] = detail.messages.map(toXMessage);
        if (activeKeyRef.current === target.key) setMessages(storeRef.current[target.key]);
      } catch {
        if (alive) {
          setLoadErrorKey(activeKeyRef.current || 'initial');
          message.error('对话历史加载失败');
        }
      } finally {
        if (alive) setConvInitialized(true);
      }
    })();
    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // 完整消息变化后防抖保存；切换会话时由操作入口立即保存旧会话。
  useEffect(() => {
    if (!convInitialized || !activeKey || messages.some((item) => item.status === 'loading')) return;
    const key = activeKey;
    const snapshot = messages;
    const timer = window.setTimeout(() => saveConversation(key, snapshot), 800);
    return () => window.clearTimeout(timer);
  }, [messages, convInitialized, activeKey, conversations, saveConversation]);

  const switchActive = (key: string) => {
    if (key === activeKey) return;
    onCancel();
    if (activeKey) saveConversation(activeKey, messages);
    ++loadVersionRef.current;
    setLoadingConversationKey('');
    setLoadErrorKey('');
    setActiveKey(key);
    selectConversation(key);
    const cached = storeRef.current[key];
    if (cached) {
      setMessages(cached);
    } else {
      setMessages([]);
      void loadConversation(Number(key));
    }
  };

  const newConversation = async () => {
    try {
      const draft = await ensureDraft();
      switchActive(draft.key);
    } catch {
      message.error('新建对话失败');
    }
  };

  useEffect(() => {
    if (!convInitialized || !location.state?.newConversation || handledRequest.current === location.key) return;
    handledRequest.current = location.key;
    navigate('/assistant', { replace: true, state: null });
    void newConversation();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [convInitialized, location.key]);

  useEffect(() => {
    if (!convInitialized || !selectedConversationKey || selectedConversationKey === activeKey) return;
    switchActive(selectedConversationKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [convInitialized, selectedConversationKey]);

  // selectedModel → modelRef 同步（agent.request 闭包读取最新值）
  useEffect(() => {
    modelRef.current = selectedModel;
  }, [selectedModel]);

  const can = usePermission();
  // 上传到知识库需要 knowledge_document:upload；无权限的账号不展示「文件」按钮
  const canUpload = can('knowledge_document:upload');

  /** 选中文件后上传到本机构知识库（可被后续提问检索引用） */
  const handleUploadFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    // 先清空 value，保证同一文件可以重复选择触发 change
    event.target.value = '';
    if (!file || uploadingFile) return;
    setUploadingFile(true);
    try {
      await uploadDocumentApi({ file, title: file.name });
      message.success(`「${file.name}」已上传到知识库，可继续向我提问`);
    } catch {
      // 错误提示已由 api.ts 全局处理
    } finally {
      setUploadingFile(false);
    }
  };

  const handleSend = (raw: string) => {
    const text = (raw ?? '').trim();
    if (!text || !activeKey || !onRequest(text)) return;
    setInput('');
    if (activeKey) {
      const activeConversation = conversations.find((item) => item.key === activeKey);
      if (activeConversation?.label === '新对话') renameConversation(activeKey, text.slice(0, 14));
    }
  };

  const renderContent = (m: XMessage) => {
    if (m.role === 'assistant' && m.status === 'loading' && !m.content) {
      return (
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: colors.textMuted }}>
          <LoadingOutlined /> 正在思考…
        </span>
      );
    }
    if (m.status === 'error') {
      return <span style={{ color: colors.error, whiteSpace: 'pre-wrap' }}>{m.content || '对话出错'}</span>;
    }
    if (m.role === 'user') return <span style={{ whiteSpace: 'pre-wrap' }}>{m.content}</span>;
    return (
      <div>
        {m.content ? (
          <XMarkdown
            content={m.content}
            className="assistant-markdown x-markdown-light"
            escapeRawHtml
            openLinksInNewTab
            streaming={{ hasNextChunk: m.status === 'loading' }}
          />
        ) : null}
        {m.status === 'stopped' ? <span className="assistant-stopped">已停止生成</span> : null}
        {m.citations?.length ? <CitationList citations={m.citations} /> : null}
      </div>
    );
  };

  const items = messages.map((m) => ({ key: m.id, role: m.role, content: renderContent(m) }));
  const isEmpty = messages.length === 0;

  return (
    <div className="assistant-page">
      <div className="assistant-workspace">
        <div className={`assistant-main${isEmpty ? ' assistant-main--empty' : ''}`}>
          {loadErrorKey === activeKey || (loadErrorKey === 'initial' && !activeKey) ? (
            <div className="assistant-welcome">
              <p>对话加载失败</p>
              <Button onClick={() => activeKey ? void loadConversation(Number(activeKey)) : window.location.reload()}>重试加载</Button>
            </div>
          ) : loadingConversationKey === activeKey && activeKey ? (
            <div className="assistant-welcome"><LoadingOutlined /> 正在加载对话…</div>
          ) : isEmpty ? (
            <div className="assistant-empty-state">
              <div className="assistant-welcome">
                <img className="assistant-welcome-avatar" src={assistantAvatar} alt="" />
                <h1>你好，我是 MedAI</h1>
                <p>基于医疗知识库的智能助手，帮助你快速获取专业信息、分析病历、辅助决策。</p>
              </div>

              <div className="assistant-capability-grid" aria-label="对话能力">
                {CAPABILITIES.map((item) => (
                  <button
                    key={item.key}
                    type="button"
                    className={`assistant-capability assistant-capability--${item.key}`}
                    onClick={() => setInput(item.prompt)}
                  >
                    <span className="assistant-capability-icon" aria-hidden="true">{item.icon}</span>
                    <span className="assistant-capability-copy">
                      <strong>{item.title}</strong>
                      <span>{item.description}</span>
                    </span>
                    <ArrowRightOutlined className="assistant-capability-arrow" aria-hidden="true" />
                  </button>
                ))}
              </div>

              <section className="assistant-suggestions" aria-labelledby="assistant-suggestions-title">
                <div className="assistant-suggestions-title" id="assistant-suggestions-title">
                  <BulbOutlined aria-hidden="true" />
                  <span>你可以这样问我</span>
                </div>
                <div className="assistant-suggestion-list">
                  {CAPABILITIES.map((item) => (
                    <button key={item.key} type="button" onClick={() => setInput(item.prompt)}>
                      <span>{item.prompt}</span>
                      <ArrowRightOutlined aria-hidden="true" />
                    </button>
                  ))}
                </div>
              </section>
            </div>
          ) : (
            <div className="assistant-messages"><Bubble.List autoScroll items={items} role={roles} /></div>
          )}
        </div>

        <div className="assistant-composer">
          <input
            ref={fileInputRef}
            type="file"
            accept={UPLOAD_ACCEPT}
            hidden
            onChange={(event) => void handleUploadFile(event)}
          />
          <Sender
            value={input}
            onChange={setInput}
            onSubmit={handleSend}
            onCancel={onCancel}
            loading={loading}
            disabled={!activeKey || loadingConversationKey === activeKey || loadErrorKey === activeKey}
            autoSize={{ minRows: 1, maxRows: 6 }}
            placeholder="发送消息..."
            suffix={false}
            footer={(_, { components: { SendButton, LoadingButton } }) => (
              <div className="assistant-composer-tools">
                <div className="assistant-composer-tools-left">
                  {canUpload ? (
                    <button
                      type="button"
                      className="assistant-tool-pill"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={uploadingFile}
                      title="上传文件到知识库"
                    >
                      {uploadingFile ? <LoadingOutlined /> : <PaperClipOutlined />}
                      <span>文件</span>
                    </button>
                  ) : null}
                  {aiConnections.length > 0 ? (
                    <Dropdown
                      trigger={['click']}
                      placement="topLeft"
                      disabled={loading}
                      menu={{
                        items: modelMenuItems,
                        selectedKeys: selectedModel ? [selectedModel] : [],
                        onClick: ({ key }) => setSelectedModel(key),
                      }}
                    >
                      <button
                        type="button"
                        className="assistant-tool-pill assistant-tool-pill--model"
                        aria-label="切换模型"
                        title="切换模型"
                      >
                        <span
                          className="assistant-model-dot"
                          style={{ background: currentModel?.color ?? MODEL_DOT_COLORS[0] }}
                        />
                        <span className="assistant-model-name">
                          {currentModel
                            ? `${currentModel.provider} / ${currentModel.model}`
                            : '选择模型'}
                        </span>
                        <DownOutlined className="assistant-tool-pill-caret" />
                      </button>
                    </Dropdown>
                  ) : null}
                </div>
                {loading ? <LoadingButton /> : <SendButton icon={<SendOutlined />} shape="circle" type="primary" />}
              </div>
            )}
          />
        </div>
      </div>
    </div>
  );
}

// med_work_admin/src/views/med/assistant/index.vue
<script lang="ts" setup>
/**
 * AI 助手会话工作台（迁移自 med-work-frontend Assistant）。
 *
 * 布局：
 *   ┌────────┬───────────────────────────────┐
 *   │ 会话栏 │  消息流 / 空态欢迎              │
 *   │  +新建 │  ──────────────────────────── │
 *   │  最近5 │  Composer（输入区 + 三工具）     │
 *   └────────┴───────────────────────────────┘
 *
 * 流式：messages 通过 useChat 管理；agent.request 转给后端 /api/chat/stream。
 * 多会话：useConversationStore 维护列表；切换会话前先保存旧消息，800ms 防抖整存。
 */
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';

import { useRoute, useRouter } from 'vue-router';

import { ElMessage } from 'element-plus';
import {
  ChatLineRound,
  Delete,
  Edit,
  Loading,
  MoreFilled,
  Plus,
  Refresh,
} from '@element-plus/icons-vue';

import Composer from '#/components/med/assistant/composer.vue';
import MessageItem from '#/components/med/assistant/message-item.vue';
import WelcomePanel from '#/components/med/assistant/welcome-panel.vue';
import PromptManagePanel from '#/components/med/prompt-manage-panel.vue';
import { getAiConnections, type AIConnectionResponse } from '#/api/med/ai';
import {
  getConversation,
  streamChat,
  updateConversation,
  type ChatCitation,
  type ChatMessageInput,
} from '#/api/med/chat';
import { listPrompts, type PromptTemplate } from '#/api/med/prompts';
import { uploadDocumentApi } from '#/api/med/documents';
import { useConversationStore } from '#/store/conversations';
import { useAccessStore } from '@vben/stores';
import { toPersist, useChat, type ChatMessage } from '#/hooks/med/use-chat';

// ==================== 会话 / 模型 / 提示词 状态 ====================

const conversationsStore = useConversationStore();
const conversations = computed(() => conversationsStore.conversations);
const activeKey = ref('');
const convInitialized = ref(false);
const loadingConversationKey = ref('');
const loadErrorKey = ref('');

const aiConnections = ref<AIConnectionResponse[]>([]);
const selectedModel = ref<null | string>(null);
const modelRef = ref<null | string>(null);
const prompts = ref<PromptTemplate[]>([]);
const selectedPromptId = ref<null | number>(null);
const convPromptMap = ref<Record<string, null | number>>({});
const messageStore = ref<Record<string, ChatMessage[]>>({});
const loadVersion = ref(0);
const saveQueue = ref<Record<string, Promise<unknown>>>({});

const inputText = ref('');
const uploadingFile = ref(false);
const manageOpen = ref(false);
const renaming = ref(false);
const renameInput = ref('');
const messagesRef = ref<HTMLDivElement | null>(null);

const accessStore = useAccessStore();
const canUpload = computed(() =>
  accessStore.accessCodes?.includes('knowledge_document:upload') ?? false,
);

const route = useRoute();
const router = useRouter();

// ==================== useChat（流式消息机） ====================

const { loading, messages, onCancel, onRequest, setMessages } = useChat({
  agent: {
    request: ({ messages: history }, cb) => {
      const persistable: ChatMessageInput[] = history
        .filter((m) => m.role === 'user' || m.status === 'done')
        .map((m) => ({
          content: m.content,
          role: m.role,
        }));
      void streamChat(persistable, {
        model: modelRef.value ?? undefined,
        onChunk: cb.onUpdate,
        onCitations: cb.onCitations,
        onDone: cb.onSuccess,
        onError: cb.onError,
        onThinking: cb.onThinking,
        signal: cb.signal,
        systemPrompt: promptContentRef.value ?? undefined,
      });
    },
  },
});

const promptContentRef = computed<string | null>(() =>
  selectedPromptId.value
    ? prompts.value.find((p) => p.id === selectedPromptId.value)?.content ?? null
    : null,
);

// 模型 → provider 元数据（圆点颜色）
const MODEL_DOT_COLORS = ['#7c4dff', '#2d6cdf', '#0b8f7f', '#c56a1a', '#d6455d'];
const modelMeta = computed(() => {
  const meta: Record<string, { color: string; provider: string }> = {};
  aiConnections.value.forEach((conn, i) => {
    const color = MODEL_DOT_COLORS[i % MODEL_DOT_COLORS.length]!;
    (conn.models ?? []).forEach((m) => {
      if (!meta[m]) meta[m] = { color, provider: conn.display_name ?? conn.provider };
    });
  });
  return meta;
});

const modelOptions = computed(() => {
  const items: { color: string; key: string; label: string }[] = [];
  for (const [modelName, meta] of Object.entries(modelMeta.value)) {
    items.push({ color: meta.color, key: modelName, label: modelName });
  }
  return items;
});

const promptOptions = computed(() => {
  const items: { key: string; label: string; type: 'default' | 'manage' | 'prompt' }[] = [
    { key: 'default', label: '默认助手', type: 'default' },
  ];
  prompts.value.forEach((p) =>
    items.push({ key: `p-${p.id}`, label: p.name, type: 'prompt' }),
  );
  items.push({ key: 'manage', label: '管理提示词…', type: 'manage' });
  return items;
});

const selectedPromptKey = computed(() =>
  selectedPromptId.value ? `p-${selectedPromptId.value}` : 'default',
);

// ==================== 副作用：AI 连接 / 提示词 ====================

onMounted(async () => {
  // AI 连接
  getAiConnections()
    .then((list) => {
      const enabled = list.filter(
        (c) => c.enabled && c.has_api_key && (c.models?.length ?? 0) > 0,
      );
      aiConnections.value = enabled;
      if (!selectedModel.value) {
        const first = enabled[0]?.active_model ?? null;
        selectedModel.value = first;
        modelRef.value = first;
      }
    })
    .catch(() => {
      /* 模型下拉为空不影响主流程 */
    });
  // 提示词
  listPrompts()
    .then((list) => {
      prompts.value = list;
    })
    .catch(() => {
      /* 下拉显示为默认助手 */
    });
  // 会话
  await initialize();
});

watch(selectedModel, (v) => {
  modelRef.value = v;
});

// ==================== 会话：初始化 / 切换 / 新建 / 删除 ====================

async function initialize() {
  try {
    const items = await conversationsStore.loadConversations();
    const requestedKey = (route.query.conversation as string | undefined) ?? undefined;
    const wantsNew = route.query.new === '1';
    let target = items[0];
    if (wantsNew) {
      target = await conversationsStore.ensureDraft();
    } else if (requestedKey) {
      target = items.find((c) => c.key === requestedKey) ?? items[0];
    } else if (conversationsStore.activeKey) {
      target = items.find((c) => c.key === conversationsStore.activeKey) ?? items[0];
    }
    if (!target) target = await conversationsStore.ensureDraft();
    setActiveKey(target.key);
  } catch {
    loadErrorKey.value = 'initial';
    ElMessage.error('对话历史加载失败');
  } finally {
    convInitialized.value = true;
  }
}

function setActiveKey(key: string) {
  activeKey.value = key;
  conversationsStore.selectConversation(key);
  const cached = messageStore.value[key];
  if (cached) {
    setMessages(cached);
  } else {
    setMessages([]);
    if (key) void loadConversation(Number(key));
  }
  // 同步提示词
  const promptId = convPromptMap.value[key];
  selectedPromptId.value = promptId ?? null;
}

async function loadConversation(id: number) {
  const key = String(id);
  const version = ++loadVersion.value;
  loadingConversationKey.value = key;
  loadErrorKey.value = '';
  try {
    const detail = await getConversation(id);
    if (version !== loadVersion.value) return;
    const list: ChatMessage[] = (detail.messages ?? []).map((m) => ({
      citations: m.citations ?? undefined,
      content: m.content,
      id: `${m.role}-${m.content.slice(0, 12)}-${Math.random().toString(36).slice(2, 7)}`,
      role: m.role === 'user' ? 'user' : 'assistant',
      status: m.role === 'assistant' ? 'done' : undefined,
    }));
    messageStore.value[key] = list;
    convPromptMap.value[key] = detail.prompt_id ?? null;
    if (activeKey.value === key) {
      selectedPromptId.value = detail.prompt_id ?? null;
      setMessages(list);
    }
  } catch {
    if (version === loadVersion.value) {
      loadErrorKey.value = key;
      ElMessage.error('会话内容加载失败');
    }
  } finally {
    if (version === loadVersion.value) loadingConversationKey.value = '';
  }
}

function switchActive(key: string) {
  if (key === activeKey.value) return;
  onCancel();
  if (activeKey.value) saveConversation(activeKey.value);
  setActiveKey(key);
}

async function newConversation() {
  try {
    const draft = await conversationsStore.ensureDraft();
    setActiveKey(draft.key);
    void router.replace({ path: '/assistant', query: {} });
  } catch {
    ElMessage.error('新建对话失败');
  }
}

async function handleDelete(key: string) {
  try {
    await conversationsStore.removeConversation(key);
    if (activeKey.value === key) {
      const next = conversations.value[0];
      if (next) setActiveKey(next.key);
      else await newConversation();
    }
  } catch {
    ElMessage.error('删除失败');
  }
}

// ==================== 保存（800ms 防抖 + 串行队列） ====================

let saveTimer: ReturnType<typeof setTimeout> | null = null;

watch(
  [messages, convInitialized, activeKey],
  () => {
    if (!convInitialized.value || !activeKey.value) return;
    if (messages.value.some((m) => m.status === 'loading')) return;
    if (saveTimer) clearTimeout(saveTimer);
    saveTimer = setTimeout(() => {
      if (activeKey.value) saveConversation(activeKey.value);
    }, 800);
  },
  { deep: true },
);

onBeforeUnmount(() => {
  if (saveTimer) clearTimeout(saveTimer);
  if (activeKey.value) void saveConversation(activeKey.value);
  onCancel();
});

async function saveConversation(key: string) {
  const list = messageStore.value[key] ?? messages.value;
  const item = conversations.value.find((c) => c.key === key);
  if (!item) return;
  const persistable = toPersist(list);
  if (!persistable.length) return;
  const previous = saveQueue.value[key] ?? Promise.resolve();
  const pending = previous.catch(() => undefined).then(() => {
    return updateConversation(Number(key), {
      messages: persistable as ChatMessageInput[],
      title: item.label,
    });
  });
  saveQueue.value[key] = pending;
  try {
    await pending;
  } catch {
    ElMessage.warning('对话保存失败，请稍后重试');
  }
}

// ==================== 发送 ====================

function handleSend(text: string) {
  if (!activeKey.value || !onRequest(text)) return;
  inputText.value = '';
  // 新对话自动按首条消息前 14 字重命名
  const item = conversations.value.find((c) => c.key === activeKey.value);
  if (item?.label === '新对话') {
    conversationsStore.renameConversation(activeKey.value, text.slice(0, 14));
  }
  nextTick(() => scrollToBottom());
}

function handlePickPrompt(key: string) {
  if (key === 'manage') {
    manageOpen.value = true;
    return;
  }
  const id = key === 'default' ? null : Number(key.slice(2));
  if (id && !prompts.value.some((p) => p.id === id)) return;
  selectedPromptId.value = id;
  if (activeKey.value) {
    convPromptMap.value[activeKey.value] = id;
    void updateConversation(Number(activeKey.value), { promptId: id ?? 0 }).catch(() => {
      /* 持久化失败仅影响下次进入 */
    });
  }
}

function handlePromptsChanged(list: PromptTemplate[]) {
  prompts.value = list;
  if (selectedPromptId.value && !list.some((p) => p.id === selectedPromptId.value)) {
    selectedPromptId.value = null;
  }
}

async function handlePickFile(file: File) {
  if (uploadingFile.value) return;
  uploadingFile.value = true;
  try {
    await uploadDocumentApi({ file, title: file.name });
    ElMessage.success(`「${file.name}」已上传到知识库，可继续向我提问`);
  } catch {
    /* request 拦截器已统一提示 */
  } finally {
    uploadingFile.value = false;
  }
}

// 把当前消息同步进 store
watch(
  messages,
  (v) => {
    if (activeKey.value) messageStore.value[activeKey.value] = v;
    nextTick(() => scrollToBottom());
  },
  { deep: true },
);

function scrollToBottom() {
  if (!messagesRef.value) return;
  messagesRef.value.scrollTop = messagesRef.value.scrollHeight;
}

// ==================== 重命名当前会话 ====================

function startRename() {
  if (!activeKey.value) return;
  const item = conversations.value.find((c) => c.key === activeKey.value);
  renameInput.value = item?.label ?? '';
  renaming.value = true;
}

async function confirmRename() {
  const name = renameInput.value.trim();
  if (!name || !activeKey.value) {
    renaming.value = false;
    return;
  }
  try {
    await updateConversation(Number(activeKey.value), { title: name });
    conversationsStore.renameConversation(activeKey.value, name);
  } catch {
    ElMessage.error('重命名失败');
  } finally {
    renaming.value = false;
  }
}

// ==================== 占位 / 上传 type ====================

const isEmpty = computed(() => messages.value.length === 0);
</script>

<template>
  <div class="med-assistant">
    <!-- 左栏：会话列表 -->
    <aside class="med-aside">
      <div class="med-aside-head">
        <el-button
          type="primary"
          :icon="Plus"
          class="med-aside-new"
          @click="newConversation"
        >
          新建对话
        </el-button>
      </div>
      <el-scrollbar class="med-aside-scroll">
        <div class="med-aside-group-title">
          <el-icon><ChatLineRound /></el-icon>
          <span>最近会话</span>
        </div>
        <ul class="med-aside-list">
          <li
            v-for="c in conversations.slice(0, 5)"
            :key="c.key"
            :class="['med-aside-item', { 'is-active': c.key === activeKey }]"
            @click="switchActive(c.key)"
          >
            <span class="med-aside-label">{{ c.label }}</span>
            <el-dropdown
              trigger="click"
              @command="(cmd: 'delete' | 'rename') => cmd === 'delete' ? handleDelete(c.key) : startRename()"
            >
              <button type="button" class="med-aside-more" @click.stop>
                <el-icon><MoreFilled /></el-icon>
              </button>
              <template #dropdown>
                <el-dropdown-menu>
                  <el-dropdown-item command="rename" :icon="Edit">重命名</el-dropdown-item>
                  <el-dropdown-item command="delete" :icon="Delete" divided>
                    <span style="color: var(--el-color-danger)">删除</span>
                  </el-dropdown-item>
                </el-dropdown-menu>
              </template>
            </el-dropdown>
          </li>
          <li v-if="!conversations.length" class="med-aside-empty">
            暂无会话
          </li>
        </ul>
      </el-scrollbar>
    </aside>

    <!-- 主区：消息流 / 欢迎 -->
    <section class="med-main">
      <header class="med-main-head">
        <div class="med-main-title">
          <template v-if="!renaming">
            <span>{{ conversations.find((c) => c.key === activeKey)?.label ?? '新对话' }}</span>
            <el-button
              v-if="activeKey"
              link
              type="primary"
              size="small"
              :icon="Edit"
              @click="startRename"
            />
          </template>
          <template v-else>
            <el-input
              v-model="renameInput"
              size="small"
              :maxlength="40"
              @keydown.enter="confirmRename"
              @keydown.esc="renaming = false"
            />
            <el-button size="small" type="primary" @click="confirmRename">保存</el-button>
            <el-button size="small" @click="renaming = false">取消</el-button>
          </template>
        </div>
        <div class="med-main-meta">
          <el-button link size="small" :icon="Refresh" @click="initialize">刷新</el-button>
        </div>
      </header>

      <div ref="messagesRef" class="med-main-scroll">
        <div v-if="loadErrorKey" class="med-main-state">
          <el-alert type="error" :closable="false" show-icon title="对话加载失败">
            <el-button @click="activeKey ? loadConversation(Number(activeKey)) : initialize()">
              重试
            </el-button>
          </el-alert>
        </div>
        <div v-else-if="loadingConversationKey === activeKey" class="med-main-state">
          <el-icon class="is-loading"><Loading /></el-icon>
          <span>正在加载对话…</span>
        </div>
        <div v-else-if="isEmpty" class="med-main-state med-main-state--empty">
          <WelcomePanel @pick="(p: string) => (inputText = p)" />
        </div>
        <div v-else class="med-main-messages">
          <MessageItem
            v-for="m in messages"
            :key="m.id"
            :role="m.role"
            :content="m.content"
            :thinking="m.thinking"
            :status="m.status"
            :citations="m.citations as ChatCitation[] | undefined"
          />
        </div>
      </div>

      <div class="med-main-composer">
        <Composer
          v-model="inputText"
          :loading="loading"
          :disabled="!activeKey || loadingConversationKey === activeKey || !!loadErrorKey"
          :can-upload="canUpload"
          :uploading-file="uploadingFile"
          :model-options="modelOptions"
          :selected-model="selectedModel"
          :prompt-options="promptOptions"
          :selected-prompt-key="selectedPromptKey"
          upload-accept=".pdf,.docx,.txt,.md"
          @send="handleSend"
          @cancel="onCancel"
          @pick-file="handlePickFile"
          @pick-model="(k: string) => (selectedModel = k)"
          @pick-prompt="handlePickPrompt"
        />
      </div>
    </section>

    <el-dialog
      v-model="manageOpen"
      title="提示词管理"
      width="760"
      :close-on-click-modal="false"
      destroy-on-close
      align-center
    >
      <PromptManagePanel :modal-width="640" @changed="handlePromptsChanged" />
    </el-dialog>
  </div>
</template>

<style scoped>
.med-assistant {
  display: flex;
  height: 100%;
  min-height: 0;
  background: linear-gradient(135deg, #eef5ff 0%, #f5f3ff 55%, #f8fbff 100%);
  border-radius: 10px;
  overflow: hidden;
}

.med-aside {
  width: 240px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  border-right: 1px solid var(--el-border-color-lighter);
  background: #fff;
}

.med-aside-head {
  padding: 14px 12px;
  border-bottom: 1px solid var(--el-border-color-lighter);
}

.med-aside-new {
  width: 100%;
}

.med-aside-scroll {
  flex: 1;
  min-height: 0;
}

.med-aside-group-title {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 10px 14px 6px;
  color: var(--el-text-color-secondary);
  font-size: 12px;
  font-weight: 600;
}

.med-aside-list {
  list-style: none;
  margin: 0;
  padding: 0 6px 12px;
}

.med-aside-item {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 8px 10px;
  border-radius: 8px;
  color: var(--el-text-color-primary);
  font-size: 13px;
  cursor: pointer;
  transition: background 160ms ease;
}

.med-aside-item:hover {
  background: var(--el-fill-color-light);
}

.med-aside-item.is-active {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
  font-weight: 600;
}

.med-aside-label {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.med-aside-more {
  display: none;
  align-items: center;
  justify-content: center;
  width: 22px;
  height: 22px;
  border: none;
  background: transparent;
  border-radius: 4px;
  color: var(--el-text-color-secondary);
  cursor: pointer;
}

.med-aside-item:hover .med-aside-more,
.med-aside-item.is-active .med-aside-more {
  display: inline-flex;
}

.med-aside-more:hover {
  background: rgb(0 0 0 / 6%);
  color: var(--el-color-primary);
}

.med-aside-empty {
  padding: 12px;
  color: var(--el-text-color-secondary);
  font-size: 12px;
  text-align: center;
}

.med-main {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.med-main-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  padding: 12px 24px;
  border-bottom: 1px solid var(--el-border-color-lighter);
  background: rgb(255 255 255 / 60%);
}

.med-main-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 15px;
  font-weight: 600;
  color: var(--el-text-color-primary);
}

.med-main-title :deep(.el-input) {
  width: 220px;
}

.med-main-meta {
  display: flex;
  align-items: center;
  gap: 6px;
}

.med-main-scroll {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding: 20px 24px;
  scrollbar-color: #cbd5e1 transparent;
  scrollbar-width: thin;
}

.med-main-state {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  min-height: 200px;
  color: var(--el-text-color-secondary);
  font-size: 13px;
}

.med-main-state--empty {
  align-items: flex-start;
  min-height: 100%;
  padding-top: 12px;
}

.med-main-messages {
  width: min(100%, 980px);
  margin: 0 auto;
  display: flex;
  flex-direction: column;
}

.med-main-composer {
  padding: 12px 24px 18px;
  border-top: 1px solid var(--el-border-color-lighter);
  background: rgb(255 255 255 / 60%);
}

.med-main-composer :deep(.med-composer) {
  max-width: 980px;
  margin: 0 auto;
}

@media (width <= 900px) {
  .med-aside {
    width: 200px;
  }
}

@media (width <= 720px) {
  .med-aside {
    display: none;
  }
}
</style>
