// med_work_admin/src/views/med/audit/index.vue
<script lang="ts" setup>
/**
 * 审计日志（迁移自 med-work-frontend Audit）：
 * 只读表格 + 筛选（关键词 / 模块 / 操作 / 结果 / 日期范围），选项来自 /audit/options。
 */
import { onMounted, ref, watch } from 'vue';

import { ElMessage } from 'element-plus';
import { Refresh, Search } from '@element-plus/icons-vue';
import dayjs from 'dayjs';

import PageHead from '#/components/med/page-head.vue';
import { getAuditLogs, getAuditOptions } from '#/api/med/audit';
import {
  AUDIT_ACTION_LABELS,
  AUDIT_MODULE_LABELS,
  AUDIT_RESULT_LABELS,
  type AuditLogItem,
} from '#/types/med';

const MODULE_TYPE: Record<string, 'danger' | 'info' | 'primary' | 'success' | 'warning'> = {
  analysis: 'warning',
  auth: 'primary',
  medical_record: 'success',
  patient: 'info',
};

const ACTION_TYPE: Record<string, 'danger' | 'info' | 'primary' | 'success' | 'warning'> = {
  create: 'success',
  delete: 'danger',
  login: 'primary',
  parse: 'warning',
  update: 'warning',
  view: 'info',
};

const RESULT_TYPE: Record<string, 'danger' | 'info' | 'success' | 'warning'> = {
  denied: 'warning',
  failure: 'danger',
  success: 'success',
};

const RESOURCE_LABELS: Record<string, string> = {
  analysis_record: '分析记录',
  medical_record: '病历记录',
  patient: '患者档案',
};

const rows = ref<AuditLogItem[]>([]);
const loading = ref(false);
const total = ref(0);
const page = ref(1);
const pageSize = ref(20);

const keyword = ref('');
const moduleCode = ref('');
const actionCode = ref('');
const resultCode = ref('');
const range = ref<[string, string] | null>(null);

const modules = ref<string[]>(Object.keys(AUDIT_MODULE_LABELS));
const actions = ref<string[]>(Object.keys(AUDIT_ACTION_LABELS));

async function loadOptions() {
  try {
    const res = await getAuditOptions();
    if (res.modules?.length) modules.value = res.modules;
    if (res.actions?.length) actions.value = res.actions;
  } catch {
    /* 回退本地常量 */
  }
}

async function load() {
  loading.value = true;
  try {
    const res = await getAuditLogs({
      action: actionCode.value || undefined,
      end_date: range.value?.[1],
      keyword: keyword.value.trim() || undefined,
      module: moduleCode.value || undefined,
      page: page.value,
      page_size: pageSize.value,
      result: resultCode.value || undefined,
      start_date: range.value?.[0],
    });
    rows.value = res.items ?? [];
    total.value = res.total ?? 0;
  } catch {
    ElMessage.error('加载审计日志失败');
  } finally {
    loading.value = false;
  }
}

onMounted(async () => {
  await loadOptions();
  await load();
});

watch([page, pageSize, moduleCode, actionCode, resultCode, range], () => {
  void load();
});

function resetFilters() {
  keyword.value = '';
  moduleCode.value = '';
  actionCode.value = '';
  resultCode.value = '';
  range.value = null;
  page.value = 1;
  void load();
}

function fmtTime(value?: null | string) {
  return value ? value.replace('T', ' ').slice(0, 19) : '—';
}

/** 日期范围选择后转成 YYYY-MM-DD 数组 */
function handleRangeChange(value: null | string[]) {
  if (!value || value.length !== 2) {
    range.value = null;
    return;
  }
  range.value = [
    dayjs(value[0]!).format('YYYY-MM-DD'),
    dayjs(value[1]!).format('YYYY-MM-DD'),
  ];
}

function resourceText(row: AuditLogItem) {
  if (!row.resource_type && !row.resource_id) return '—';
  if (row.resource_id) {
    const label = RESOURCE_LABELS[row.resource_type ?? ''] ?? row.resource_type ?? '';
    return `${label} ${row.resource_id}`.trim();
  }
  return row.resource_type ?? '—';
}
</script>

<template>
  <div class="med-page">
    <div class="med-page-inner">
      <PageHead
        :crumbs="[{ label: '系统管理' }, { label: '审计日志', current: true }]"
        title="审计日志"
        subtitle="记录登录、患者档案 / 病历 / AI 分析等关键操作的完整轨迹（仅管理员与审计员可见）"
      />

      <el-card shadow="never">
        <div class="audit-filters">
          <el-input
            v-model="keyword"
            clearable
            placeholder="搜索账号 / 姓名 / 摘要"
            class="audit-search"
            :prefix-icon="Search"
            @keyup.enter="page = 1; load()"
          />
          <el-select
            v-model="moduleCode"
            clearable
            placeholder="全部模块"
            class="audit-select"
            @change="page = 1"
          >
            <el-option
              v-for="m in modules"
              :key="m"
              :label="AUDIT_MODULE_LABELS[m] ?? m"
              :value="m"
            />
          </el-select>
          <el-select
            v-model="actionCode"
            clearable
            placeholder="全部操作"
            class="audit-select"
            @change="page = 1"
          >
            <el-option
              v-for="a in actions"
              :key="a"
              :label="AUDIT_ACTION_LABELS[a] ?? a"
              :value="a"
            />
          </el-select>
          <el-select
            v-model="resultCode"
            clearable
            placeholder="全部结果"
            class="audit-select audit-select--sm"
            @change="page = 1"
          >
            <el-option label="成功" value="success" />
            <el-option label="失败" value="failure" />
            <el-option label="拒绝" value="denied" />
          </el-select>
          <el-date-picker
            :model-value="range"
            type="daterange"
            value-format="YYYY-MM-DD"
            start-placeholder="开始日期"
            end-placeholder="结束日期"
            @change="(v: null | string[]) => handleRangeChange(v)"
          />
          <el-button text @click="resetFilters">重置</el-button>
          <el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button>
          <span class="audit-total">共 {{ total }} 条记录</span>
        </div>

        <el-table v-loading="loading" :data="rows" row-key="id" border stripe>
          <el-table-column label="时间" prop="created_at" width="170">
            <template #default="{ row }">
              <span class="audit-mono">{{ fmtTime(row.created_at) }}</span>
            </template>
          </el-table-column>
          <el-table-column label="操作者" width="150">
            <template #default="{ row }">
              <div class="audit-actor">
                <span class="audit-actor-name">{{ row.real_name || row.username || '—' }}</span>
                <span
                  v-if="row.username && row.username !== row.real_name"
                  class="audit-sub"
                >
                  @{{ row.username }}
                </span>
              </div>
            </template>
          </el-table-column>
          <el-table-column label="模块" prop="module" width="110">
            <template #default="{ row }">
              <el-tag :type="MODULE_TYPE[row.module] ?? 'info'" size="small">
                {{ AUDIT_MODULE_LABELS[row.module] ?? row.module }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="操作" prop="action" width="100">
            <template #default="{ row }">
              <el-tag :type="ACTION_TYPE[row.action] ?? 'info'" size="small">
                {{ AUDIT_ACTION_LABELS[row.action] ?? row.action }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="资源" width="170">
            <template #default="{ row }">
              <span class="audit-mono">{{ resourceText(row) }}</span>
            </template>
          </el-table-column>
          <el-table-column label="摘要" prop="detail" min-width="220" show-overflow-tooltip>
            <template #default="{ row }">
              <span>{{ row.detail || '—' }}</span>
            </template>
          </el-table-column>
          <el-table-column label="结果" prop="result" width="90">
            <template #default="{ row }">
              <el-tag :type="RESULT_TYPE[row.result] ?? 'info'" size="small">
                {{ AUDIT_RESULT_LABELS[row.result] ?? row.result }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="来源 IP" prop="ip" width="140">
            <template #default="{ row }">
              <span class="audit-mono">{{ row.ip || '—' }}</span>
            </template>
          </el-table-column>
          <template #empty>
            <el-empty description="暂无符合条件的审计记录" :image-size="60" />
          </template>
        </el-table>

        <div class="audit-pager">
          <el-pagination
            v-model:current-page="page"
            v-model:page-size="pageSize"
            :page-sizes="[10, 20, 50, 100]"
            :total="total"
            layout="total, sizes, prev, pager, next"
            background
          />
        </div>
      </el-card>
    </div>
  </div>
</template>

<style scoped>
.med-page {
  height: 100%;
  padding: 20px;
  overflow-y: auto;
}

.med-page-inner {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.audit-filters {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  margin-bottom: 12px;
}

.audit-search {
  width: 240px;
}

.audit-select {
  width: 140px;
}

.audit-select--sm {
  width: 120px;
}

.audit-total {
  margin-left: auto;
  color: var(--el-text-color-secondary);
  font-size: 12px;
}

.audit-mono {
  font-family: var(--el-font-family-monospace, Consolas, monospace);
  font-size: 12px;
  color: var(--el-text-color-regular);
}

.audit-actor {
  display: flex;
  flex-direction: column;
  line-height: 1.4;
}

.audit-actor-name {
  font-size: 13px;
  font-weight: 600;
}

.audit-sub {
  color: var(--el-text-color-secondary);
  font-size: 11px;
}

.audit-pager {
  display: flex;
  justify-content: flex-end;
  margin-top: 12px;
}
</style>

// med_work_frontend/src/pages/Audit/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  App as AntApp,
  Button,
  Card,
  DatePicker,
  Input,
  Select,
  Table,
  Tag,
  Tooltip,
} from 'antd';
import { ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import type { Dayjs } from 'dayjs';
import { PageHead } from '@/components';
import { colors } from '@/theme';
import { getAuditLogs, getAuditOptions } from '@/services/audit';
import {
  AUDIT_ACTION_LABELS,
  AUDIT_MODULE_LABELS,
  AUDIT_RESULT_LABELS,
  type AuditLogItem,
} from '@/types';

const { RangePicker } = DatePicker;

/** 模块 Tag 颜色 */
const MODULE_COLOR: Record<string, string> = {
  auth: 'geekblue',
  patient: 'blue',
  medical_record: 'cyan',
  analysis: 'purple',
};

/** 操作 Tag 颜色 */
const ACTION_COLOR: Record<string, string> = {
  login: 'geekblue',
  logout: 'default',
  register: 'cyan',
  view: 'blue',
  create: 'green',
  update: 'orange',
  delete: 'red',
  parse: 'purple',
};

/** 结果 Tag 颜色 */
const RESULT_COLOR: Record<string, string> = {
  success: 'green',
  failure: 'red',
  denied: 'orange',
};

/** 资源类型中文名 */
const RESOURCE_LABELS: Record<string, string> = {
  patient: '患者档案',
  medical_record: '病历记录',
  analysis_record: '分析记录',
};

/** ISO 时间 → 本地展示串 */
function formatTime(iso: string): string {
  if (!iso) return '-';
  return iso.replace('T', ' ').slice(0, 19);
}

function toOptions(codes: string[], labels: Record<string, string>) {
  return codes.map((code) => ({ value: code, label: labels[code] ?? code }));
}

export default function Audit() {
  const { message } = AntApp.useApp();

  // ---------- 筛选选项（后端兜底为主，异常时回退本地常量） ----------
  const [modules, setModules] = useState<string[]>(Object.keys(AUDIT_MODULE_LABELS));
  const [actions, setActions] = useState<string[]>(Object.keys(AUDIT_ACTION_LABELS));

  // ---------- 筛选条件 ----------
  const [loading, setLoading] = useState(false);
  const [rows, setRows] = useState<AuditLogItem[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [keyword, setKeyword] = useState('');
  const [module, setModule] = useState('');
  const [action, setAction] = useState('');
  const [result, setResult] = useState('');
  const [range, setRange] = useState<[Dayjs, Dayjs] | null>(null);

  useEffect(() => {
    getAuditOptions()
      .then((res) => {
        if (res.modules.length) setModules(res.modules);
        if (res.actions.length) setActions(res.actions);
      })
      .catch(() => undefined);
  }, []);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getAuditLogs({
        page,
        page_size: pageSize,
        keyword: keyword.trim() || undefined,
        module: module || undefined,
        action: action || undefined,
        result: result || undefined,
        start_date: range?.[0]?.format('YYYY-MM-DD'),
        end_date: range?.[1]?.format('YYYY-MM-DD'),
      });
      setRows(res.items);
      setTotal(res.total);
    } catch (error) {
      message.error(error instanceof Error ? error.message : '加载审计日志失败');
    } finally {
      setLoading(false);
    }
  }, [page, pageSize, keyword, module, result, action, range, message]);

  useEffect(() => {
    load();
  }, [load]);

  const columns = useMemo<ColumnsType<AuditLogItem>>(
    () => [
      {
        title: '时间',
        dataIndex: 'created_at',
        key: 'created_at',
        width: 165,
        render: (v: string) => (
          <span className="mono" style={{ fontSize: 12, color: colors.textSecondary }}>
            {formatTime(v)}
          </span>
        ),
      },
      {
        title: '操作者',
        key: 'actor',
        width: 150,
        render: (_: unknown, r: AuditLogItem) => (
          <div>
            <div style={{ fontWeight: 600, fontSize: 13 }}>
              {r.real_name || r.username || '—'}
            </div>
            {r.username && r.username !== r.real_name && (
              <div className="text-muted" style={{ fontSize: 11 }}>
                @{r.username}
              </div>
            )}
          </div>
        ),
      },
      {
        title: '模块',
        dataIndex: 'module',
        key: 'module',
        width: 110,
        render: (v: string) => (
          <Tag color={MODULE_COLOR[v] ?? 'default'} style={{ marginInlineEnd: 0 }}>
            {AUDIT_MODULE_LABELS[v] ?? v}
          </Tag>
        ),
      },
      {
        title: '操作',
        dataIndex: 'action',
        key: 'action',
        width: 100,
        render: (v: string) => (
          <Tag color={ACTION_COLOR[v] ?? 'default'} style={{ marginInlineEnd: 0 }}>
            {AUDIT_ACTION_LABELS[v] ?? v}
          </Tag>
        ),
      },
      {
        title: '资源',
        key: 'resource',
        width: 170,
        render: (_: unknown, r: AuditLogItem) => {
          if (!r.resource_type && !r.resource_id) return <span className="text-muted">—</span>;
          return (
            <span className="mono" style={{ fontSize: 12 }}>
              {r.resource_id
                ? `${RESOURCE_LABELS[r.resource_type ?? ''] ?? r.resource_type ?? ''} ${r.resource_id}`
                : r.resource_type}
            </span>
          );
        },
      },
      {
        title: '摘要',
        dataIndex: 'detail',
        key: 'detail',
        ellipsis: true,
        render: (v: string | null) =>
          v ? (
            <Tooltip title={v}>
              <span style={{ fontSize: 13 }}>{v}</span>
            </Tooltip>
          ) : (
            <span className="text-muted">—</span>
          ),
      },
      {
        title: '结果',
        dataIndex: 'result',
        key: 'result',
        width: 80,
        render: (v: string) => (
          <Tag color={RESULT_COLOR[v] ?? 'default'} style={{ marginInlineEnd: 0 }}>
            {AUDIT_RESULT_LABELS[v] ?? v}
          </Tag>
        ),
      },
      {
        title: '来源 IP',
        dataIndex: 'ip',
        key: 'ip',
        width: 135,
        render: (v: string | null) => (
          <span className="mono" style={{ fontSize: 12 }}>
            {v || '—'}
          </span>
        ),
      },
    ],
    [],
  );

  return (
    <div className="workbench-page">
      <PageHead
        crumbs={[]}
        title="审计日志"
        subtitle="记录登录、患者档案 / 病历 / AI 分析等关键操作的完整轨迹（仅管理员与审计员可见）"
      />

      <Card styles={{ body: { padding: 0 } }}>
        <div style={{ padding: '16px 20px', display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          <Input
            prefix={<SearchOutlined style={{ color: colors.textMuted }} />}
            placeholder="搜索账号 / 姓名 / 摘要"
            allowClear
            style={{ width: 240 }}
            value={keyword}
            onChange={(e) => {
              setKeyword(e.target.value);
              setPage(1);
            }}
          />
          <Select
            placeholder="全部模块"
            style={{ width: 140 }}
            allowClear
            value={module || undefined}
            onChange={(v) => {
              setModule(v ?? '');
              setPage(1);
            }}
            options={toOptions(modules, AUDIT_MODULE_LABELS)}
          />
          <Select
            placeholder="全部操作"
            style={{ width: 130 }}
            allowClear
            value={action || undefined}
            onChange={(v) => {
              setAction(v ?? '');
              setPage(1);
            }}
            options={toOptions(actions, AUDIT_ACTION_LABELS)}
          />
          <Select
            placeholder="全部结果"
            style={{ width: 120 }}
            allowClear
            value={result || undefined}
            onChange={(v) => {
              setResult(v ?? '');
              setPage(1);
            }}
            options={[
              { value: 'success', label: '成功' },
              { value: 'failure', label: '失败' },
              { value: 'denied', label: '拒绝' },
            ]}
          />
          <RangePicker
            value={range ?? undefined}
            onChange={(values) => {
              setRange(values && values[0] && values[1] ? [values[0], values[1]] : null);
              setPage(1);
            }}
            placeholder={['开始日期', '结束日期']}
          />
          <Button icon={<ReloadOutlined />} onClick={() => load()}>
            刷新
          </Button>
        </div>
        <Table<AuditLogItem>
          rowKey="id"
          loading={loading}
          columns={columns}
          dataSource={rows}
          scroll={{ x: 1080 }}
          pagination={{
            current: page,
            pageSize,
            total,
            showSizeChanger: true,
            pageSizeOptions: [10, 20, 50, 100],
            showTotal: (t) => (
              <span className="text-muted" style={{ fontSize: 12 }}>
                共 {t} 条记录
              </span>
            ),
            onChange: (p, ps) => {
              setPage(p);
              setPageSize(ps);
            },
          }}
        />
      </Card>
    </div>
  );
}
