// med_work_admin/src/components/med/page-head.vue
<script lang="ts" setup>
/**
 * 页头（迁移自 med-work-frontend PageHead）：面包屑 + 标题 + 副标题 + 右侧操作区
 */
defineProps<{
  /** 面包屑 */
  crumbs?: Array<{ current?: boolean; label: string }>;
  /** 紧凑模式：缩小标题字号与间距，适用于满高工作台页面 */
  dense?: boolean;
  /** 副标题 */
  subtitle?: string;
  /** 标题 */
  title: string;
}>();
</script>

<template>
  <div class="page-head" :class="{ dense }">
    <div class="page-head-main">
      <el-breadcrumb v-if="crumbs?.length" separator="/">
        <el-breadcrumb-item v-for="(crumb, index) in crumbs" :key="index">
          {{ crumb.label }}
        </el-breadcrumb-item>
      </el-breadcrumb>
      <div class="page-head-title" :class="{ dense }">{{ title }}</div>
      <div v-if="subtitle" class="page-head-subtitle">{{ subtitle }}</div>
    </div>
    <div v-if="$slots.actions" class="page-head-actions">
      <slot name="actions" />
    </div>
  </div>
</template>

<style scoped>
.page-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 16px;
}

.page-head-main {
  flex: 1;
  min-width: 0;
}

.page-head-title {
  margin: 6px 0 0;
  font-size: 20px;
  font-weight: 600;
  line-height: 1.4;
}

.page-head-title.dense {
  margin-top: 2px;
  font-size: 16px;
}

.page-head-subtitle {
  margin-top: 4px;
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.page-head-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}
</style>

// med_work_frontend/src/components/PageHead/index.tsx
import type { ReactNode } from 'react';
import { Breadcrumb, Flex, Typography } from 'antd';

export interface Crumb {
  label: string;
  current?: boolean;
}

export interface PageHeadProps {
  crumbs: Crumb[];
  title: string;
  subtitle?: string;
  actions?: ReactNode;
  /** 紧凑模式：缩小标题字号与间距，适用于满高工作台页面 */
  dense?: boolean;
}

export default function PageHead({ crumbs, title, subtitle, actions, dense }: PageHeadProps) {
  const items = crumbs.map((c) => ({ title: c.label }));
  return (
    <Flex align="flex-start" justify="space-between" gap={16} wrap>
      <div style={{ flex: 1, minWidth: 0 }}>
        <Breadcrumb items={items} />
        <Typography.Title level={dense ? 5 : 4} style={{ margin: dense ? '2px 0 0' : '6px 0 0' }}>
          {title}
        </Typography.Title>
        {subtitle && (
          <Typography.Text type="secondary" style={{ display: 'block', marginTop: 4, fontSize: 13 }}>
            {subtitle}
          </Typography.Text>
        )}
      </div>
      {actions && (
        <Flex align="center" gap={10}>
          {actions}
        </Flex>
      )}
    </Flex>
  );
}
