// med_work_frontend/src/pages/Documents/components/LocalDocumentDetailDrawer.tsx
/**
 * 本地文档详情抽屉：元信息 + 分块列表（对接 /api/knowledge/documents/{id}）。
 */
import { Alert, Descriptions, Drawer, Empty, List, Spin, Tag } from 'antd';
import { FileTextOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';

import { TypeTag } from '@/components';
import { useDictionaryOptions } from '@/hooks';
import { colors } from '@/theme';
import { getDocumentDetailApi } from '@/services/knowledge';
import {
  DICT_DOC_TYPE,
  DICT_INDEX_STATUS,
  DICT_SOURCE_TYPE,
  FALLBACK_DOC_TYPE_OPTIONS,
  FALLBACK_INDEX_STATUS_OPTIONS,
  FALLBACK_SOURCE_TYPE_OPTIONS,
} from '@/constants/dictionary';
import type { DocumentDetailResponse } from '@/types';

/** 索引状态 → Tag 颜色（颜色是 UI 关注点，不进字典） */
const STATUS_COLOR: Record<string, string> = {
  uploaded: 'default',
  ready: 'success',
  parsing: 'warning',
  failed: 'error',
};

function formatBytes(n: number): string {
  if (!n) return '0 B';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function formatTime(s: string): string {
  return s ? s.replace('T', ' ').slice(0, 19) : '-';
}

interface LocalDocumentDetailDrawerProps {
  /** 当前查看的文档 ID；null 时抽屉关闭 */
  docId: number | null;
  onClose: () => void;
}

export default function LocalDocumentDetailDrawer({
  docId,
  onClose,
}: LocalDocumentDetailDrawerProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [detail, setDetail] = useState<DocumentDetailResponse | null>(null);

  // 字典选项：类型 / 状态 / 来源分类
  const { labels: docTypeLabels } = useDictionaryOptions(DICT_DOC_TYPE, FALLBACK_DOC_TYPE_OPTIONS);
  const { labels: statusLabels } = useDictionaryOptions(DICT_INDEX_STATUS, FALLBACK_INDEX_STATUS_OPTIONS);
  const { labels: sourceTypeLabels } = useDictionaryOptions(DICT_SOURCE_TYPE, FALLBACK_SOURCE_TYPE_OPTIONS);

  useEffect(() => {
    if (docId == null) {
      setDetail(null);
      setError(null);
      return;
    }
    let alive = true;
    setLoading(true);
    setError(null);
    setDetail(null);
    (async () => {
      try {
        const res = await getDocumentDetailApi(docId);
        if (alive) setDetail(res);
      } catch {
        if (alive) setError('文档详情加载失败，请稍后重试');
      } finally {
        if (alive) setLoading(false);
      }
    })();
    return () => {
      alive = false;
    };
  }, [docId]);

  const doc = detail?.document ?? null;

  return (
    <Drawer
      title={doc?.title ?? '文档详情'}
      open={docId != null}
      onClose={onClose}
      width={760}
    >
      {loading ? (
        <div style={{ textAlign: 'center', padding: 48 }}>
          <Spin />
        </div>
      ) : error ? (
        <Alert type="error" showIcon message={error} />
      ) : !doc ? (
        <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无数据" />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Descriptions
            size="small"
            column={2}
            bordered
            items={[
              {
                key: 'type',
                label: '类型',
                children: <TypeTag type={docTypeLabels[doc.doc_type] ?? doc.doc_type} />,
              },
              {
                key: 'status',
                label: '状态',
                children: (
                  <Tag color={STATUS_COLOR[doc.status] ?? 'default'} style={{ marginInlineEnd: 0 }}>
                    {statusLabels[doc.status] ?? '处理中'}
                  </Tag>
                ),
              },
              {
                key: 'file',
                label: '文件名',
                span: 2,
                children: (
                  <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                    <FileTextOutlined style={{ color: colors.primary }} />
                    {doc.file_name}
                  </span>
                ),
              },
              {
                key: 'source',
                label: '来源',
                children: (
                  <span>
                    {doc.source_type === 'ima' ? (
                      <Tag color="geekblue" style={{ marginInlineEnd: 0 }}>
                        {sourceTypeLabels['ima'] ?? 'IMA'}
                      </Tag>
                    ) : (
                      doc.source || '-'
                    )}
                  </span>
                ),
              },
              {
                key: 'size',
                label: '大小',
                children: formatBytes(doc.file_size),
              },
              {
                key: 'chunks',
                label: '分块 / 向量',
                children: `${doc.chunk_count} 分块 / ${doc.vector_count} 向量`,
              },
              {
                key: 'uploader',
                label: '上传人',
                children: doc.created_by || '-',
              },
              {
                key: 'time',
                label: '上传时间',
                children: formatTime(doc.created_at),
              },
              {
                key: 'updated',
                label: '更新时间',
                children: formatTime(doc.updated_at),
              },
              ...(doc.remark
                ? [
                    {
                      key: 'remark',
                      label: '备注',
                      span: 2,
                      children: doc.remark,
                    },
                  ]
                : []),
            ]}
          />

          {doc.error_message && (
            <Alert type="error" showIcon message="索引失败原因" description={doc.error_message} />
          )}

          <div>
            <div
              style={{
                fontWeight: 600,
                fontSize: 13,
                marginBottom: 8,
                color: colors.text,
              }}
            >
              文本分块（{detail?.chunks?.length ?? 0}）
            </div>
            {(detail?.chunks?.length ?? 0) === 0 ? (
              <Empty
                image={Empty.PRESENTED_IMAGE_SIMPLE}
                description="该文档暂无文本分块（可能仍在解析或索引失败）"
              />
            ) : (
              <List
                size="small"
                dataSource={detail?.chunks ?? []}
                renderItem={(chunk) => (
                  <List.Item style={{ alignItems: 'flex-start' }}>
                    <div style={{ width: '100%' }}>
                      {chunk.title && (
                        <div style={{ fontWeight: 600, fontSize: 12, marginBottom: 4 }}>
                          {chunk.title}
                        </div>
                      )}
                      <div className="text-muted" style={{ fontSize: 12, marginBottom: 4 }}>
                        分块 #{chunk.chunk_index} · {chunk.char_count} 字
                      </div>
                      <div
                        style={{
                          fontSize: 12,
                          lineHeight: 1.7,
                          whiteSpace: 'pre-wrap',
                          wordBreak: 'break-word',
                          color: colors.textSecondary,
                          maxHeight: 120,
                          overflow: 'auto',
                        }}
                      >
                        {chunk.content}
                      </div>
                    </div>
                  </List.Item>
                )}
              />
            )}
          </div>
        </div>
      )}
    </Drawer>
  );
}

// med_work_admin/src/components/med/local-document-detail-drawer.vue
<script lang="ts" setup>
/**
 * 本地文档详情抽屉：元信息 + 分块列表。
 * 迁移自 med-work-frontend LocalDocumentDetailDrawer。
 */
import { onMounted, ref, watch } from 'vue';

import { ElMessage } from 'element-plus';
import {
  Document as DocumentIcon,
} from '@element-plus/icons-vue';

import { downloadDocumentFile, getDocumentDetailApi } from '#/api/med/documents';
import {
  DICT_DOC_TYPE,
  DICT_INDEX_STATUS,
  DICT_SOURCE_TYPE,
  FALLBACK_DOC_TYPE_OPTIONS,
  FALLBACK_INDEX_STATUS_OPTIONS,
  FALLBACK_SOURCE_TYPE_OPTIONS,
} from '#/constants/med/dictionary';
import type { DocumentDetailResponse } from '#/types/med';

import { useDictionaryOptions } from '#/hooks/use-dictionary-options';

const STATUS_TAG_TYPE: Record<string, 'primary' | 'success' | 'warning' | 'danger' | 'info'> = {
  uploaded: 'info',
  ready: 'success',
  parsing: 'warning',
  failed: 'danger',
};

function formatBytes(n: number): string {
  if (!n) return '0 B';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function formatTime(s?: string): string {
  return s ? s.replace('T', ' ').slice(0, 19) : '-';
}

interface Props {
  /** 当前查看的文档 ID；null 时抽屉关闭 */
  docId: number | null;
  onClose: () => void;
}

const props = defineProps<Props>();

const { labels: docTypeLabels } = useDictionaryOptions(
  DICT_DOC_TYPE,
  FALLBACK_DOC_TYPE_OPTIONS,
);
const { labels: statusLabels } = useDictionaryOptions(
  DICT_INDEX_STATUS,
  FALLBACK_INDEX_STATUS_OPTIONS,
);
const { labels: sourceTypeLabels } = useDictionaryOptions(
  DICT_SOURCE_TYPE,
  FALLBACK_SOURCE_TYPE_OPTIONS,
);

const loading = ref(false);
const error = ref('');
const detail = ref<DocumentDetailResponse | null>(null);

async function load(id: number) {
  loading.value = true;
  error.value = '';
  detail.value = null;
  try {
    detail.value = await getDocumentDetailApi(id);
  } catch (e) {
    error.value =
      e instanceof Error ? e.message : '文档详情加载失败，请稍后重试';
  } finally {
    loading.value = false;
  }
}

watch(
  () => props.docId,
  (id) => {
    if (id != null) void load(id);
    else {
      detail.value = null;
      error.value = '';
    }
  },
  { immediate: true },
);

onMounted(() => {
  if (props.docId != null) void load(props.docId);
});

const doc = () => detail.value?.document ?? null;

async function handleDownload() {
  const current = doc();
  if (!current) return;
  try {
    await downloadDocumentFile(current.id, current.file_name);
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '下载失败');
  }
}
</script>

<template>
  <el-drawer
    :model-value="docId != null"
    :title="doc()?.title ?? '文档详情'"
    size="640"
    direction="rtl"
    @update:model-value="onClose"
  >
    <div v-loading="loading" class="med-doc-detail">
      <el-alert
        v-if="error"
        :title="error"
        type="error"
        :closable="false"
        show-icon
      />

      <template v-else-if="doc()">
        <el-descriptions :column="2" size="small" border>
          <el-descriptions-item label="类型">
            {{ docTypeLabels[doc()!.doc_type] ?? doc()!.doc_type }}
          </el-descriptions-item>
          <el-descriptions-item label="状态">
            <el-tag :type="STATUS_TAG_TYPE[doc()!.status] ?? 'info'" size="small">
              {{ statusLabels[doc()!.status] ?? '处理中' }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="文件名" :span="2">
            <span class="med-doc-file">
              <el-icon style="color: var(--el-color-primary)">
                <DocumentIcon />
              </el-icon>
              {{ doc()!.file_name }}
            </span>
          </el-descriptions-item>
          <el-descriptions-item label="来源">
            <span v-if="doc()!.source_type === 'ima'">
              <el-tag type="primary" size="small">
                {{ sourceTypeLabels['ima'] ?? 'IMA' }}
              </el-tag>
            </span>
            <span v-else>{{ doc()!.source || '—' }}</span>
          </el-descriptions-item>
          <el-descriptions-item label="大小">
            {{ formatBytes(doc()!.file_size) }}
          </el-descriptions-item>
          <el-descriptions-item label="分块 / 向量" :span="2">
            {{ doc()!.chunk_count }} 分块 / {{ doc()!.vector_count }} 向量
          </el-descriptions-item>
          <el-descriptions-item label="上传人">
            {{ doc()!.created_by || '—' }}
          </el-descriptions-item>
          <el-descriptions-item label="上传时间">
            <span class="med-mono">{{ formatTime(doc()!.created_at) }}</span>
          </el-descriptions-item>
          <el-descriptions-item label="更新时间" :span="2">
            <span class="med-mono">{{ formatTime(doc()!.updated_at) }}</span>
          </el-descriptions-item>
          <el-descriptions-item
            v-if="doc()!.remark"
            label="备注"
            :span="2"
          >
            {{ doc()!.remark }}
          </el-descriptions-item>
        </el-descriptions>

        <el-alert
          v-if="doc()!.error_message"
          type="error"
          show-icon
          title="索引失败原因"
          :description="doc()!.error_message"
          class="med-doc-error"
        />

        <div class="med-doc-chunks">
          <div class="med-doc-chunks-head">
            <span>文本分块（{{ detail?.chunks?.length ?? 0 }}）</span>
            <el-button
              type="primary"
              size="small"
              :icon="DocumentIcon"
              @click="handleDownload"
            >
              下载原文件
            </el-button>
          </div>
          <el-empty
            v-if="!(detail?.chunks?.length ?? 0)"
            description="该文档暂无文本分块（可能仍在解析或索引失败）"
            :image-size="80"
          />
          <el-scrollbar v-else max-height="40vh">
            <div
              v-for="chunk in detail?.chunks ?? []"
              :key="chunk.id"
              class="med-doc-chunk"
            >
              <div v-if="chunk.title" class="med-doc-chunk-title">
                {{ chunk.title }}
              </div>
              <div class="med-doc-chunk-meta">
                分块 #{{ chunk.chunk_index }} · {{ chunk.char_count }} 字
              </div>
              <div class="med-doc-chunk-content">{{ chunk.content }}</div>
            </div>
          </el-scrollbar>
        </div>
      </template>

      <el-empty
        v-else-if="!loading"
        description="暂无数据"
        :image-size="80"
      />
    </div>
  </el-drawer>
</template>

<style scoped>
.med-doc-detail {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.med-doc-file {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  word-break: break-all;
}

.med-doc-error {
  margin: 0;
}

.med-doc-chunks {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.med-doc-chunks-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-weight: 600;
  font-size: 13px;
}

.med-doc-chunk {
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  padding: 10px 12px;
  background: var(--el-fill-color-light);
}

.med-doc-chunk-title {
  font-weight: 600;
  font-size: 12.5px;
  margin-bottom: 4px;
}

.med-doc-chunk-meta {
  color: var(--el-text-color-secondary);
  font-size: 11.5px;
  margin-bottom: 4px;
}

.med-doc-chunk-content {
  font-size: 12.5px;
  line-height: 1.7;
  color: var(--el-text-color-secondary);
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 100px;
  overflow: auto;
}

.med-mono {
  font-family: var(--el-font-family-monospace, 'SFMono-Regular', Consolas, monospace);
}
</style>
