// med_work_frontend/src/pages/Documents/components/LocalDocumentTable.tsx
/**
 * 本地知识库列表：展示 med_documents 中的本地文档（本地上传 system + IMA 搬运 ima）。
 * 文档类型筛选由父级「文档管理」左侧菜单控制（docType 受控传入），
 * 本组件提供关键词 / 状态筛选、分页、详情、重新索引与删除。
 * 自管状态，直接调用 services，与「上传任务」抽屉互不干扰。
 */
import {
  App as AntApp,
  Button,
  Dropdown,
  Empty,
  Input,
  Select,
  Table,
  Tag,
  Tooltip,
} from 'antd';
import {
  FileTextOutlined,
  MoreOutlined,
  PlayCircleOutlined,
  ReloadOutlined,
  SearchOutlined,
  UndoOutlined,
} from '@ant-design/icons';
import { useCallback, useEffect, useMemo, useState } from 'react';

import { TypeTag } from '@/components';
import { useDictionaryOptions } from '@/hooks';
import { colors } from '@/theme';
import { usePermission } from '@/utils/access';
import {
  deleteDocumentApi,
  listDocumentsApi,
  reindexDocumentApi,
} from '@/services/knowledge';
import {
  DICT_DOC_TYPE,
  DICT_INDEX_STATUS,
  DICT_SOURCE_TYPE,
  FALLBACK_DOC_TYPE_OPTIONS,
  FALLBACK_INDEX_STATUS_OPTIONS,
  FALLBACK_SOURCE_TYPE_OPTIONS,
} from '@/constants/dictionary';
import type { KnowledgeDocument } from '@/types';
import LocalDocumentDetailDrawer from './LocalDocumentDetailDrawer';

/** 索引状态 → Tag 颜色（颜色是 UI 关注点，不进字典） */
const STATUS_COLOR: Record<string, string> = {
  uploaded: 'default',
  ready: 'success',
  parsing: 'warning',
  failed: 'error',
};

function formatBytes(n: number): string {
  if (!n) return '0 B';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function formatTime(s: string): string {
  return s ? s.replace('T', ' ').slice(0, 16) : '-';
}

interface LocalDocumentTableProps {
  /** 外部刷新信号（如上传成功），值变化时重新加载列表 */
  refreshKey?: number;
  /** 文档类型筛选（由父级左侧菜单控制；undefined 表示全部） */
  docType?: string;
  /** 类型筛选变化回调（重置时用于清除类型） */
  onDocTypeChange?: (v: string | undefined) => void;
}

export default function LocalDocumentTable({
  refreshKey = 0,
  docType,
  onDocTypeChange,
}: LocalDocumentTableProps) {
  const { message, modal } = AntApp.useApp();
  const can = usePermission();

  // ---------- 字典选项（文档类型 / 索引状态 / 来源分类由字典维护） ----------
  const { labels: docTypeLabels } = useDictionaryOptions(DICT_DOC_TYPE, FALLBACK_DOC_TYPE_OPTIONS);
  const { options: statusOptions, labels: statusLabels } = useDictionaryOptions(
    DICT_INDEX_STATUS,
    FALLBACK_INDEX_STATUS_OPTIONS,
  );
  // 来源标签仍用于列表「来源」列展示，但不提供来源筛选
  const { labels: sourceTypeLabels } = useDictionaryOptions(
    DICT_SOURCE_TYPE,
    FALLBACK_SOURCE_TYPE_OPTIONS,
  );

  // ---------- 筛选条件（本地独立状态，不污染上传任务抽屉） ----------
  // 输入/选择即查询：keyword 防抖写入，Select 变更直接触发 load
  const [keywordInput, setKeywordInput] = useState('');
  const [keyword, setKeyword] = useState('');
  const [status, setStatus] = useState<string | undefined>();

  // ---------- 列表数据 ----------
  const [items, setItems] = useState<KnowledgeDocument[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [loading, setLoading] = useState(false);

  // ---------- 详情抽屉 ----------
  const [detailId, setDetailId] = useState<number | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const data = await listDocumentsApi({
        keyword: keyword.trim() || undefined,
        doc_type: docType,
        status,
        page,
        page_size: pageSize,
      });
      setItems(data.items);
      setTotal(data.total);
    } catch {
      message.error('文档列表加载失败，请稍后重试');
    } finally {
      setLoading(false);
    }
  }, [keyword, docType, status, page, pageSize, message]);

  useEffect(() => {
    void load();
  }, [load, refreshKey]);

  // 关键词防抖：停止输入 350ms 后自动查询（输入即搜）
  useEffect(() => {
    const t = window.setTimeout(() => {
      setKeyword(keywordInput);
      setPage(1);
    }, 350);
    return () => window.clearTimeout(t);
  }, [keywordInput]);

  // 存在处理中任务时轮询刷新进度
  const hasParsing = useMemo(() => items.some((d) => d.status === 'parsing'), [items]);
  useEffect(() => {
    if (!hasParsing) return;
    const t = window.setInterval(() => void load(), 3000);
    return () => window.clearInterval(t);
  }, [hasParsing, load]);

  /** 查询按钮：立即应用输入框关键词（不等防抖） */
  const handleSearch = useCallback(() => {
    setKeyword(keywordInput);
    setPage(1);
  }, [keywordInput]);

  const handleReset = useCallback(() => {
    setKeywordInput('');
    setKeyword('');
    setStatus(undefined);
    setPage(1);
    onDocTypeChange?.(undefined);
  }, [onDocTypeChange]);

  const confirmDelete = useCallback(
    (doc: KnowledgeDocument) => {
      modal.confirm({
        title: '删除文档',
        content: `确定删除「${doc.title}」吗？将同时清除其向量与分块，且不可恢复。`,
        okText: '删除',
        okButtonProps: { danger: true },
        cancelText: '取消',
        onOk: async () => {
          try {
            await deleteDocumentApi(doc.id);
            message.success(`「${doc.title}」已删除`);
            void load();
          } catch {
            message.error('删除失败，请稍后重试');
          }
        },
      });
    },
    [modal, message, load],
  );

  const handleReindex = async (doc: KnowledgeDocument) => {
    try {
      await reindexDocumentApi(doc.id);
      message.success(`「${doc.title}」已提交重新索引`);
      void load();
    } catch {
      message.error('重新索引提交失败，请稍后重试');
    }
  };

  const columns = [
    {
      title: '文档名称',
      key: 'name',
      render: (_: unknown, r: KnowledgeDocument) => (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 }}>
          <FileTextOutlined style={{ color: colors.primary, fontSize: 18, flexShrink: 0 }} />
          <div style={{ minWidth: 0 }}>
            <div
              style={{
                fontWeight: 600,
                fontSize: 13,
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}
            >
              {r.title}
            </div>
            <div className="text-muted" style={{ fontSize: 11 }}>
              {r.file_name}
            </div>
          </div>
        </div>
      ),
    },
    {
      title: '类型',
      dataIndex: 'doc_type',
      key: 'doc_type',
      width: 104,
      render: (v: string) => <TypeTag type={docTypeLabels[v] ?? v} />,
    },
    {
      title: '来源',
      dataIndex: 'source',
      key: 'source',
      width: 104,
      ellipsis: true,
      render: (v: string, r: KnowledgeDocument) =>
        r.source_type === 'ima' ? (
          <Tag color="geekblue" style={{ marginInlineEnd: 0 }}>
            {sourceTypeLabels['ima'] ?? 'IMA'}
          </Tag>
        ) : (
          <Tooltip title={v}>
            <span className="text-muted" style={{ fontSize: 12 }}>
              {v || '-'}
            </span>
          </Tooltip>
        ),
    },
    {
      title: '大小',
      dataIndex: 'file_size',
      key: 'file_size',
      width: 82,
      render: (v: number) => (
        <span className="mono" style={{ fontSize: 12, color: colors.textSecondary }}>
          {formatBytes(v)}
        </span>
      ),
    },
    {
      title: '分块',
      dataIndex: 'chunk_count',
      key: 'chunk_count',
      width: 68,
      render: (v: number) => (
        <span className="mono" style={{ fontSize: 12 }}>
          {v}
        </span>
      ),
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 88,
      render: (v: string) => (
        <Tag color={STATUS_COLOR[v] ?? 'default'} style={{ marginInlineEnd: 0 }}>
          {statusLabels[v] ?? '处理中'}
        </Tag>
      ),
    },
    {
      title: '上传时间',
      dataIndex: 'created_at',
      key: 'created_at',
      width: 136,
      render: (v: string) => (
        <span className="mono" style={{ fontSize: 12, color: colors.textSecondary }}>
          {formatTime(v)}
        </span>
      ),
    },
    {
      title: '',
      key: 'action',
      width: 56,
      render: (_: unknown, r: KnowledgeDocument) => (
        <Dropdown
          trigger={['click']}
          menu={{
            items: [
              {
                key: 'detail',
                label: '查看详情',
                icon: <PlayCircleOutlined />,
                onClick: () => setDetailId(r.id),
              },
              ...(can('knowledge_document:update')
                ? [
                    {
                      key: 'reindex',
                      label: '重新索引',
                      icon: <ReloadOutlined />,
                      disabled: r.status === 'parsing',
                      onClick: () => handleReindex(r),
                    },
                  ]
                : []),
              ...(can('knowledge_document:update') || can('knowledge_document:delete')
                ? [{ type: 'divider' as const }]
                : []),
              ...(can('knowledge_document:delete')
                ? [
                    {
                      key: 'delete',
                      label: <span style={{ color: colors.error }}>删除文档</span>,
                      danger: true,
                      onClick: () => confirmDelete(r),
                    },
                  ]
                : []),
            ],
          }}
        >
          <Button type="text" size="small" icon={<MoreOutlined />} />
        </Dropdown>
      ),
    },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, height: '100%', minWidth: 0 }}>
      {/* 筛选工具栏 */}
      <div className="doc-toolbar">
        <Input
          prefix={<SearchOutlined />}
          placeholder="搜索标题 / 文件名"
          allowClear
          style={{ width: 220 }}
          value={keywordInput}
          onChange={(e) => setKeywordInput(e.target.value)}
          onPressEnter={handleSearch}
        />
        <Select
          placeholder="索引状态"
          allowClear
          style={{ width: 120 }}
          options={statusOptions}
          value={status}
          onChange={(v) => {
            setStatus(v);
            setPage(1);
          }}
        />
        <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
          查询
        </Button>
        <Button icon={<UndoOutlined />} onClick={handleReset}>
          重置
        </Button>
        {hasParsing && (
          <span className="text-muted" style={{ fontSize: 12 }}>
            存在处理中的文档，列表将自动刷新…
          </span>
        )}
      </div>

      {/* 列表 */}
      <div className="doc-content-scroll">
        <Table
          rowKey="id"
          loading={loading}
          size="middle"
          columns={columns}
          dataSource={items}
          scroll={{ x: 900 }}
          pagination={{
            current: page,
            pageSize,
            total,
            showSizeChanger: true,
            showTotal: (t) => `共 ${t} 篇`,
            onChange: (p, ps) => {
              setPage(p);
              setPageSize(ps);
            },
          }}
          locale={{
            emptyText: (
              <Empty
                image={Empty.PRESENTED_IMAGE_SIMPLE}
                description="暂无文档，点击右上角「上传文档」添加"
              />
            ),
          }}
        />
      </div>

      <LocalDocumentDetailDrawer docId={detailId} onClose={() => setDetailId(null)} />
    </div>
  );
}

// med_work_admin/src/components/med/local-document-table.vue
<script lang="ts" setup>
/**
 * 本地知识库文档列表（迁移自 med-work-frontend LocalDocumentTable）：
 * 关键词 / 状态筛选、分页、详情、下载、重新索引与删除，存在处理中任务时轮询。
 */
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';

import {
  ElMessage,
  ElMessageBox,
} from 'element-plus';
import {
  Delete,
  Download,
  MoreFilled,
  Refresh,
  Search,
  View,
  Switch,
  VideoPlay,
} from '@element-plus/icons-vue';

import LocalDocumentDetailDrawer from '#/components/med/local-document-detail-drawer.vue';
import {
  deleteDocumentApi,
  downloadDocumentFile,
  listDocumentsApi,
  reindexDocumentApi,
  startDocumentIndexApi,
} from '#/api/med/documents';
import {
  DICT_DOC_TYPE,
  DICT_INDEX_STATUS,
  DICT_SOURCE_TYPE,
  FALLBACK_DOC_TYPE_OPTIONS,
  FALLBACK_INDEX_STATUS_OPTIONS,
  FALLBACK_SOURCE_TYPE_OPTIONS,
} from '#/constants/med/dictionary';
import type { KnowledgeDocument } from '#/types/med';

import { useDictionaryOptions } from '#/hooks/use-dictionary-options';

const STATUS_TAG_TYPE: Record<string, 'primary' | 'success' | 'warning' | 'danger' | 'info'> = {
  uploaded: 'info',
  ready: 'success',
  parsing: 'warning',
  failed: 'danger',
};

function formatBytes(n: number): string {
  if (!n) return '0 B';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function formatTime(s: string): string {
  return s ? s.replace('T', ' ').slice(0, 16) : '-';
}

interface Props {
  refreshKey?: number;
  /** 文档类型筛选（undefined 表示全部） */
  docType?: string;
  onDocTypeChange?: (v: string | undefined) => void;
}

const props = withDefaults(defineProps<Props>(), {
  refreshKey: 0,
  docType: undefined,
  onDocTypeChange: undefined,
});

const { labels: docTypeLabels, options: docTypeOptions } = useDictionaryOptions(
  DICT_DOC_TYPE,
  FALLBACK_DOC_TYPE_OPTIONS,
);
const { options: statusOptions, labels: statusLabels } = useDictionaryOptions(
  DICT_INDEX_STATUS,
  FALLBACK_INDEX_STATUS_OPTIONS,
);
const { labels: sourceTypeLabels } = useDictionaryOptions(
  DICT_SOURCE_TYPE,
  FALLBACK_SOURCE_TYPE_OPTIONS,
);

const keywordInput = ref('');
const keyword = ref('');
const status = ref<string | undefined>(undefined);
const page = ref(1);
const pageSize = ref(10);
const total = ref(0);
const items = ref<KnowledgeDocument[]>([]);
const loading = ref(false);
const detailId = ref<null | number>(null);

async function load() {
  loading.value = true;
  try {
    const res = await listDocumentsApi({
      doc_type: props.docType,
      keyword: keyword.value.trim() || undefined,
      page: page.value,
      page_size: pageSize.value,
      status: status.value,
    });
    items.value = res.items;
    total.value = res.total;
  } finally {
    loading.value = false;
  }
}

onMounted(load);

watch(
  () => [props.refreshKey, props.docType],
  () => {
    page.value = 1;
    load();
  },
);

let keywordTimer: ReturnType<typeof setTimeout> | null = null;
watch(keywordInput, (v) => {
  if (keywordTimer) clearTimeout(keywordTimer);
  keywordTimer = setTimeout(() => {
    keyword.value = v;
    page.value = 1;
    load();
  }, 350);
});

const hasParsing = computed(() => items.value.some((d) => d.status === 'parsing'));
let pollTimer: ReturnType<typeof setInterval> | null = null;
watch(
  hasParsing,
  (v) => {
    if (pollTimer) {
      clearInterval(pollTimer);
      pollTimer = null;
    }
    if (v) {
      pollTimer = setInterval(() => load(), 3000);
    }
  },
  { immediate: true },
);

onUnmounted(() => {
  if (pollTimer) clearInterval(pollTimer);
  if (keywordTimer) clearTimeout(keywordTimer);
});

function handleReset() {
  keywordInput.value = '';
  keyword.value = '';
  status.value = undefined;
  page.value = 1;
  props.onDocTypeChange?.(undefined);
}

async function handleDownload(doc: KnowledgeDocument) {
  try {
    await downloadDocumentFile(doc.id, doc.file_name);
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '下载失败');
  }
}

async function handleReindex(doc: KnowledgeDocument) {
  try {
    await reindexDocumentApi(doc.id);
    ElMessage.success(`「${doc.title}」已提交重新索引`);
    load();
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '重新索引提交失败');
  }
}

async function handleStartIndex(doc: KnowledgeDocument) {
  try {
    await startDocumentIndexApi(doc.id);
    ElMessage.success(`「${doc.title}」已开始索引，请稍候查看进度`);
    load();
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '提交失败');
  }
}

async function handleDelete(doc: KnowledgeDocument) {
  try {
    await ElMessageBox.confirm(
      `确定删除「${doc.title}」吗？将同时清除其向量与分块，且不可恢复。`,
      '删除文档',
      { confirmButtonText: '删除', cancelButtonText: '取消', type: 'warning' },
    );
  } catch {
    return;
  }
  try {
    await deleteDocumentApi(doc.id);
    ElMessage.success(`「${doc.title}」已删除`);
    load();
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : '删除失败');
  }
}
</script>

<template>
  <div class="med-doc-table">
    <div class="med-doc-toolbar">
      <el-input
        v-model="keywordInput"
        :prefix-icon="Search"
        placeholder="搜索标题 / 文件名"
        clearable
        class="med-doc-search"
      />
      <el-select
        v-model="status"
        placeholder="索引状态"
        clearable
        class="med-doc-status"
        @change="page = 1; load()"
      >
        <el-option
          v-for="o in statusOptions"
          :key="o.value"
          :label="o.label"
          :value="o.value"
        />
      </el-select>
      <el-select
        :model-value="props.docType"
        placeholder="文档类型"
        clearable
        class="med-doc-type"
        @change="(v: string | undefined) => { props.onDocTypeChange?.(v ?? undefined); page = 1; load(); }"
      >
        <el-option
          v-for="o in docTypeOptions"
          :key="o.value"
          :label="o.label"
          :value="o.value"
        />
      </el-select>
      <el-button :icon="Refresh" @click="load()">刷新</el-button>
      <el-button @click="handleReset">重置</el-button>
      <span v-if="hasParsing" class="med-doc-poll-tip">
        存在处理中的文档，列表将自动刷新…
      </span>
    </div>

    <el-table
      v-loading="loading"
      :data="items"
      row-key="id"
    >
      <el-table-column label="文档" min-width="280">
        <template #default="{ row }">
          <div class="med-doc-cell">
            <el-icon class="med-doc-cell-icon" style="color: var(--el-color-primary)">
              <Search />
            </el-icon>
            <div class="med-doc-cell-meta">
              <div class="med-doc-cell-title" :title="row.title">{{ row.title }}</div>
              <div class="med-doc-cell-sub">{{ row.file_name }}</div>
            </div>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="类型" width="110">
        <template #default="{ row }">
          <el-tag size="small" effect="plain">
            {{ docTypeLabels[row.doc_type] ?? row.doc_type }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="来源" width="110">
        <template #default="{ row }">
          <el-tag
            v-if="row.source_type === 'ima'"
            type="primary"
            size="small"
            effect="plain"
          >
            {{ sourceTypeLabels['ima'] ?? 'IMA' }}
          </el-tag>
          <el-tooltip v-else :content="row.source || '—'" placement="top">
            <span class="med-doc-source">{{ row.source || '—' }}</span>
          </el-tooltip>
        </template>
      </el-table-column>
      <el-table-column label="大小" width="100">
        <template #default="{ row }">
          <span class="med-mono med-text-meta">{{ formatBytes(row.file_size) }}</span>
        </template>
      </el-table-column>
      <el-table-column label="分块" width="80">
        <template #default="{ row }">
          <span class="med-mono">{{ row.chunk_count }}</span>
        </template>
      </el-table-column>
      <el-table-column label="状态" width="100">
        <template #default="{ row }">
          <el-tag :type="STATUS_TAG_TYPE[row.status] ?? 'info'" size="small">
            {{ statusLabels[row.status] ?? '处理中' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="上传时间" width="150">
        <template #default="{ row }">
          <span class="med-mono med-text-meta">{{ formatTime(row.created_at) }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="120" align="right" fixed="right">
        <template #default="{ row }">
          <el-button
            link
            type="primary"
            :icon="View"
            size="small"
            @click="detailId = row.id"
          >
            详情
          </el-button>
          <el-dropdown trigger="click">
            <el-button link type="primary" :icon="MoreFilled" size="small" />
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item :icon="Download" @click="handleDownload(row)">
                  下载原文件
                </el-dropdown-item>
                <el-dropdown-item
                  v-if="row.status === 'uploaded'"
                  v-access:code="'knowledge_document:index'"
                  :icon="VideoPlay"
                  @click="handleStartIndex(row)"
                >
                  开始索引
                </el-dropdown-item>
                <el-dropdown-item
                  v-else
                  v-access:code="'knowledge_document:update'"
                  :icon="Switch"
                  :disabled="row.status === 'parsing'"
                  @click="handleReindex(row)"
                >
                  重新索引
                </el-dropdown-item>
                <el-dropdown-item
                  v-access:code="'knowledge_document:delete'"
                  :icon="Delete"
                  divided
                  @click="handleDelete(row)"
                >
                  <span style="color: var(--el-color-danger)">删除文档</span>
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </el-table>

    <div class="med-doc-pagination">
      <el-pagination
        v-model:current-page="page"
        v-model:page-size="pageSize"
        :page-sizes="[10, 20, 50]"
        :total="total"
        background
        layout="total, sizes, prev, pager, next, jumper"
        @current-change="load()"
        @size-change="load()"
      >
        <template #total>共 {{ total }} 篇</template>
      </el-pagination>
    </div>

    <LocalDocumentDetailDrawer
      :doc-id="detailId"
      :on-close="() => (detailId = null)"
    />
  </div>
</template>

<style scoped>
.med-doc-table {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.med-doc-toolbar {
  display: flex;
  gap: 10px;
  align-items: center;
  flex-wrap: wrap;
}

.med-doc-search {
  width: 220px;
}

.med-doc-status {
  width: 120px;
}

.med-doc-type {
  width: 140px;
}

.med-doc-poll-tip {
  color: var(--el-text-color-secondary);
  font-size: 12px;
  margin-left: auto;
}

.med-doc-cell {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.med-doc-cell-icon {
  flex-shrink: 0;
  font-size: 18px;
}

.med-doc-cell-meta {
  min-width: 0;
}

.med-doc-cell-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--el-text-color-primary);
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.med-doc-cell-sub {
  font-size: 11px;
  color: var(--el-text-color-secondary);
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

.med-doc-source {
  color: var(--el-text-color-secondary);
  font-size: 12px;
  overflow: hidden;
  text-overflow: ellipsis;
  display: inline-block;
  max-width: 100%;
  white-space: nowrap;
  vertical-align: middle;
}

.med-doc-pagination {
  display: flex;
  justify-content: flex-end;
}

.med-mono {
  font-family: var(--el-font-family-monospace, 'SFMono-Regular', Consolas, monospace);
}

.med-text-meta {
  color: var(--el-text-color-secondary);
  font-size: 12px;
}
</style>
