// med_work_admin/src/components/med/analysis-evolution.vue
<script lang="ts" setup>
/**
 * 分析演变：对比该患者历次 AI 分析中的关注点等级轨迹与诊断结论变化。
 * 迁移自 med-work-frontend AnalysisEvolution。
 */
import { onMounted, ref } from 'vue';

import {
  ArrowDown,
  ArrowUp,
  MagicStick,
  Minus,
  Plus,
} from '@element-plus/icons-vue';

import { getPatientAnalysisEvolution } from '#/api/med/patients';
import type {
  AnalysisEvolutionResponse,
  AttentionTrendItem,
} from '#/types/med';

const LEVEL_COLOR: Record<string, 'danger' | 'warning' | 'primary' | 'info'> = {
  高: 'danger',
  中: 'warning',
  低: 'primary',
};

const TREND_META: Record<
  string,
  { label: string; color: 'danger' | 'success' | 'info' | 'warning'; icon: 'up' | 'down' | 'flat' | 'new' }
> = {
  up: { label: '加重 ↑', color: 'danger', icon: 'up' },
  down: { label: '减轻 ↓', color: 'success', icon: 'down' },
  flat: { label: '持平', color: 'info', icon: 'flat' },
  new: { label: '新出现', color: 'warning', icon: 'new' },
};

function formatTime(iso: string): string {
  return iso ? iso.replace('T', ' ').slice(0, 16) : '-';
}

interface Props {
  patientId: number;
}

const props = defineProps<Props>();

const data = ref<AnalysisEvolutionResponse | null>(null);
const loading = ref(false);

async function load() {
  loading.value = true;
  try {
    data.value = await getPatientAnalysisEvolution(props.patientId);
  } catch {
    data.value = null;
  } finally {
    loading.value = false;
  }
}

onMounted(load);

function trendMeta(trend: string) {
  return TREND_META[trend] ?? TREND_META.flat!;
}

function trendIcon(name: string) {
  if (name === 'up') return ArrowUp;
  if (name === 'down') return ArrowDown;
  if (name === 'new') return Plus;
  return Minus; // 'flat' 用 - 图标
}

function fullLabel(row: AttentionTrendItem) {
  const full = row.points.length;
  const last = row.points[full - 1];
  if (full > 0 && last && row.latest_level) {
    return `共 ${full} 次 · ${formatTime(last.time).slice(5)}`;
  }
  return `共 ${full} 次`;
}
</script>

<template>
  <div v-loading="loading" class="med-evo">
    <template v-if="data && (data.analyses ?? []).length">
      <el-card shadow="never" class="med-evo-card">
        <template #header>
          <div class="med-evo-head">
            <el-icon style="color: #722ed1"><MagicStick /></el-icon>
            <span>关注点变化</span>
            <span class="med-evo-sub">
              共 {{ (data.attention_trend ?? []).length }} 个关注点，按出现频次排序
            </span>
          </div>
        </template>
        <el-empty
          v-if="!(data.attention_trend ?? []).length"
          description="分析结论中暂无结构化关注点"
          :image-size="80"
        />
        <el-table
          v-else
          :data="data.attention_trend"
          row-key="title"
          size="small"
        >
          <el-table-column label="关注点" min-width="200">
            <template #default="{ row }">
              <span class="med-evo-title">{{ row.title }}</span>
            </template>
          </el-table-column>
          <el-table-column label="出现" width="200" align="center">
            <template #default="{ row }">
              <span class="med-evo-meta">{{ fullLabel(row as AttentionTrendItem) }}</span>
            </template>
          </el-table-column>
          <el-table-column label="等级轨迹" min-width="240">
            <template #default="{ row }">
              <el-tag
                v-for="(point, index) in (row as AttentionTrendItem).points"
                :key="index"
                :type="LEVEL_COLOR[point.level] ?? 'info'"
                size="small"
                class="med-evo-level"
                :title="formatTime(point.time)"
              >
                {{ point.level || '—' }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="趋势" width="100">
            <template #default="{ row }">
              <el-tag :type="trendMeta((row as AttentionTrendItem).trend).color" size="small">
                <el-icon class="med-evo-trend-icon"><component :is="trendIcon(trendMeta((row as AttentionTrendItem).trend).icon)" /></el-icon>
                {{ trendMeta((row as AttentionTrendItem).trend).label }}
              </el-tag>
            </template>
          </el-table-column>
        </el-table>
      </el-card>

      <el-card shadow="never" class="med-evo-card">
        <template #header>
          <div class="med-evo-head">
            <el-icon style="color: #722ed1"><MagicStick /></el-icon>
            <span>诊断结论演变</span>
            <span class="med-evo-sub">共 {{ (data.diagnosis_timeline ?? []).length }} 条</span>
          </div>
        </template>
        <el-empty
          v-if="!(data.diagnosis_timeline ?? []).length"
          description="分析结论中暂无诊断类条目"
          :image-size="80"
        />
        <el-timeline v-else>
          <el-timeline-item
            v-for="(point, index) in data.diagnosis_timeline"
            :key="`${point.analysis_id}-${index}`"
            :type="index === (data.diagnosis_timeline ?? []).length - 1 ? 'success' : 'primary'"
            placement="top"
          >
            <div class="med-evo-diag-row">
              <span class="med-evo-diag-key">{{ point.key }}</span>
              <el-tag type="success" size="small">分析 #{{ point.analysis_id }}</el-tag>
              <span class="med-evo-meta">{{ formatTime(point.time) }}</span>
            </div>
            <p class="med-evo-diag-text">{{ point.value }}</p>
          </el-timeline-item>
        </el-timeline>
      </el-card>
    </template>

    <el-card v-else-if="!loading" shadow="never">
      <el-empty description="暂无已完成的分析，暂无法对比演变">
        <el-text type="info" size="small">
          完成至少两次 AI 分析后，此处将展示关注点与诊断结论的变化轨迹。
        </el-text>
      </el-empty>
    </el-card>
  </div>
</template>

<style scoped>
.med-evo {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.med-evo-card :deep(.el-card__body) {
  padding: 0;
}

.med-evo-head {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
}

.med-evo-sub {
  color: var(--el-text-color-secondary);
  font-size: 12px;
  font-weight: 400;
}

.med-evo-meta {
  color: var(--el-text-color-secondary);
  font-size: 12px;
}

.med-evo-title {
  font-weight: 600;
}

.med-evo-level {
  margin-right: 4px;
}

.med-evo-trend-icon {
  vertical-align: -2px;
  margin-right: 2px;
}

.med-evo-diag-row {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 4px;
}

.med-evo-diag-key {
  font-weight: 600;
  font-size: 13px;
}

.med-evo-diag-text {
  font-size: 13px;
  line-height: 1.6;
  margin: 0;
  color: var(--el-text-color-secondary);
  white-space: pre-wrap;
}
</style>

// med_work_frontend/src/pages/Patients/components/AnalysisEvolution.tsx
import { useCallback, useEffect, useState } from 'react';
import { Card, Empty, Flex, Spin, Table, Tag, Timeline, Tooltip, Typography } from 'antd';
import {
  ArrowDownOutlined,
  ArrowUpOutlined,
  MinusOutlined,
  PlusOutlined,
  RobotOutlined,
} from '@ant-design/icons';
import { colors } from '@/theme';
import { ANALYSIS_TYPES, type AnalysisEvolutionResponse } from '@/types';
import { getPatientAnalysisEvolution } from '@/services/patients';

const TYPE_LABEL: Record<string, string> = Object.fromEntries(
  ANALYSIS_TYPES.map((item) => [item.value, item.label]),
);

/** 关注点等级 → 颜色 */
const LEVEL_COLOR: Record<string, string> = {
  高: 'red',
  中: 'orange',
  低: 'blue',
};

const TREND_META: Record<string, { label: string; color: string; icon?: React.ReactNode }> = {
  up: { label: '加重 ↑', color: 'red', icon: <ArrowUpOutlined /> },
  down: { label: '减轻 ↓', color: 'green', icon: <ArrowDownOutlined /> },
  flat: { label: '持平', color: 'default', icon: <MinusOutlined /> },
  new: { label: '新出现', color: 'purple', icon: <PlusOutlined /> },
};

function formatTime(iso: string): string {
  return iso ? iso.replace('T', ' ').slice(0, 16) : '-';
}

interface AnalysisEvolutionProps {
  patientId: number;
}

/**
 * 分析演变：对比该患者历次 AI 分析中的关注点等级轨迹与诊断结论变化。
 * 数据来自 GET /api/patients/{id}/analysis-evolution。
 */
export default function AnalysisEvolution({ patientId }: AnalysisEvolutionProps) {
  const [data, setData] = useState<AnalysisEvolutionResponse | null>(null);
  const [loading, setLoading] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getPatientAnalysisEvolution(patientId);
      setData(res);
    } catch {
      setData(null);
    } finally {
      setLoading(false);
    }
  }, [patientId]);

  useEffect(() => {
    load();
  }, [load]);

  if (loading) {
    return (
      <Card>
        <div style={{ textAlign: 'center', padding: 48 }}>
          <Spin />
        </div>
      </Card>
    );
  }

  const analyses = data?.analyses ?? [];
  const trend = data?.attention_trend ?? [];
  const diagnosis = data?.diagnosis_timeline ?? [];

  if (!analyses.length) {
    return (
      <Card>
        <Empty description="暂无已完成的分析，暂无法对比演变" style={{ padding: '72px 0' }}>
          <Typography.Text type="secondary" style={{ fontSize: 12 }}>
            完成至少两次 AI 分析后，此处将展示关注点与诊断结论的变化轨迹。
          </Typography.Text>
        </Empty>
      </Card>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <Card
        size="small"
        title={
          <Flex align="center" gap={8}>
            <RobotOutlined style={{ color: colors.ai }} />
            <span>关注点变化</span>
            <span className="text-muted" style={{ fontSize: 12, fontWeight: 400 }}>
              共 {trend.length} 个关注点，按出现频次排序
            </span>
          </Flex>
        }
      >
        {trend.length === 0 ? (
          <Empty
            image={Empty.PRESENTED_IMAGE_SIMPLE}
            description="分析结论中暂无结构化关注点"
            style={{ padding: '24px 0' }}
          />
        ) : (
          <Table
            rowKey="title"
            size="small"
            pagination={false}
            dataSource={trend}
            columns={[
              {
                title: '关注点',
                dataIndex: 'title',
                ellipsis: true,
                render: (text: string) => <Typography.Text strong>{text}</Typography.Text>,
              },
              {
                title: '出现',
                dataIndex: 'points',
                align: 'center',
                width: 180,
                render: (_: unknown, row) => {
                  const full = row.points.length;
                  const item = row.points[full - 1];
                  return (
                    <span className="text-muted" style={{ fontSize: 12 }}>
                      共 {full} 次{full > 0 && item && row.latest_level ? ` · ${formatTime(item.time).slice(5)}` : ''}
                    </span>
                  );
                },
              },
              {
                title: '等级轨迹',
                dataIndex: 'points',
                render: (points: { time: string; level: string }[]) => (
                  <Flex gap={4} wrap="wrap">
                    {points.map((point, index) => (
                      <Tooltip key={index} title={formatTime(point.time)}>
                        <Tag color={LEVEL_COLOR[point.level] ?? 'default'} style={{ marginInlineEnd: 0 }}>
                          {point.level || '—'}
                        </Tag>
                      </Tooltip>
                    ))}
                  </Flex>
                ),
              },
              {
                title: '趋势',
                dataIndex: 'trend',
                width: 90,
                render: (value: string) => {
                  const meta = TREND_META[value] ?? TREND_META.flat;
                  return <Tag color={meta.color}>{meta.label}</Tag>;
                },
              },
            ]}
          />
        )}
      </Card>

      <Card
        size="small"
        title={
          <Flex align="center" gap={8}>
            <RobotOutlined style={{ color: colors.ai }} />
            <span>诊断结论演变</span>
            <span className="text-muted" style={{ fontSize: 12, fontWeight: 400 }}>
              共 {diagnosis.length} 条
            </span>
          </Flex>
        }
      >
        {diagnosis.length === 0 ? (
          <Empty
            image={Empty.PRESENTED_IMAGE_SIMPLE}
            description="分析结论中暂无诊断类条目"
            style={{ padding: '24px 0' }}
          />
        ) : (
          <Timeline
            items={diagnosis.map((point, index) => ({
              color: index === diagnosis.length - 1 ? 'green' : 'blue',
              children: (
                <div key={`${point.analysis_id}-${index}`}>
                  <Flex align="center" gap={8} wrap="wrap" style={{ marginBottom: 4 }}>
                    <span style={{ fontWeight: 600, fontSize: 13 }}>{point.key}</span>
                    <Tag color="purple" style={{ marginInlineEnd: 0 }}>
                      分析 #{point.analysis_id}
                    </Tag>
                    <span className="text-muted" style={{ fontSize: 11.5 }}>
                      {formatTime(point.time)}
                    </span>
                  </Flex>
                  <Typography.Paragraph
                    style={{ fontSize: 13, lineHeight: 1.6, marginBottom: 0, color: colors.textSecondary }}
                    ellipsis={{ rows: 3, expandable: true, symbol: '展开' }}
                  >
                    {point.value}
                  </Typography.Paragraph>
                </div>
              ),
            }))}
          />
        )}
      </Card>
    </div>
  );
}
