// med_work_admin/src/components/med/report-export-modal.vue
<script lang="ts" setup>
/**
 * 导出患者诊疗分析报告（Word / PDF）。
 * 迁移自 med-work-frontend ReportExportModal：多选患者 + 可选时间范围。
 */
import { ref, watch } from 'vue';

import { ElMessage } from 'element-plus';
import { Document, Download, InfoFilled } from '@element-plus/icons-vue';

import { downloadPatientReport } from '#/api/med/patients';
import type { PatientReportRange, ReportFormat } from '#/types/med';

export interface ReportCandidate {
  id: number;
  name: string;
  patient_no: string;
}

interface Props {
  open: boolean;
  candidates: ReportCandidate[];
  /** 打开时预选中的患者 ID */
  defaultIds?: number[];
  /** 锁定选择（详情页导出当前患者时无需再选） */
  lockSelection?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  defaultIds: () => [],
  lockSelection: false,
});

const emit = defineEmits<{
  (e: 'update:open', v: boolean): void;
  (e: 'close'): void;
}>();

const ids = ref<number[]>([]);
const range = ref<[string, string] | null>(null);
const format = ref<ReportFormat>('docx');
const submitting = ref(false);

watch(
  () => props.open,
  (v) => {
    if (!v) return;
    ids.value = [...(props.defaultIds ?? [])];
    range.value = null;
    format.value = 'docx';
  },
);

async function handleOk() {
  if (!ids.value.length) {
    ElMessage.warning('请选择要导出的患者');
    return;
  }
  submitting.value = true;
  try {
    const payload: PatientReportRange = {
      start_date: range.value?.[0] ?? undefined,
      end_date: range.value?.[1] ?? undefined,
    };
    // 逐个 await：避免并发触发浏览器的多文件下载拦截
    for (const id of ids.value) {
      await downloadPatientReport(id, payload, format.value);
    }
    ElMessage.success(
      ids.value.length > 1 ? `已导出 ${ids.value.length} 份报告` : '报告已开始下载',
    );
    emit('update:open', false);
    emit('close');
  } finally {
    submitting.value = false;
  }
}

function close() {
  emit('update:open', false);
  emit('close');
}
</script>

<template>
  <el-dialog
    :model-value="open"
    title="导出患者诊疗分析报告"
    :width="480"
    :close-on-click-modal="false"
    destroy-on-close
    @update:model-value="emit('update:open', $event)"
    @close="close"
  >
    <div class="report-export-body">
      <div class="report-export-row">
        <div class="report-export-label">导出格式</div>
        <el-radio-group v-model="format">
          <el-radio-button value="docx">Word（可编辑再打印）</el-radio-button>
          <el-radio-button value="pdf">PDF（版式固定）</el-radio-button>
        </el-radio-group>
      </div>

      <div class="report-export-row">
        <div class="report-export-label">
          选择患者<span v-if="!lockSelection">（可多选）</span>
        </div>
        <el-select
          v-if="!lockSelection"
          v-model="ids"
          multiple
          filterable
          placeholder="请选择患者"
          style="width: 100%"
        >
          <el-option
            v-for="item in candidates"
            :key="item.id"
            :value="item.id"
            :label="`${item.name}　${item.patient_no}`"
          />
        </el-select>
        <el-select
          v-else
          :model-value="ids[0]"
          disabled
          style="width: 100%"
        >
          <el-option
            v-for="item in candidates"
            :key="item.id"
            :value="item.id"
            :label="`${item.name}　${item.patient_no}`"
          />
        </el-select>
      </div>

      <div class="report-export-row">
        <div class="report-export-label">时间范围（可选）</div>
        <el-date-picker
          v-model="range"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          value-format="YYYY-MM-DD"
          style="width: 100%"
        />
      </div>

      <el-text type="info" size="small">
        <el-icon style="vertical-align: -2px"><InfoFilled /></el-icon>
        报告包含患者基本信息、所选时间范围内的全部病历记录与 AI 分析（结论 / 关注点 /
        循证依据），导出为可编辑的 Word 文档；留空时间范围表示导出全部记录。
      </el-text>
    </div>
    <template #footer>
      <el-button @click="close">取消</el-button>
      <el-button
        type="primary"
        :loading="submitting"
        :icon="format === 'pdf' ? Download : Document"
        @click="handleOk"
      >
        {{ format === 'pdf' ? '导出 PDF' : '导出 Word' }}
      </el-button>
    </template>
  </el-dialog>
</template>

<style scoped>
.report-export-body {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-top: 4px;
}

.report-export-row {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.report-export-label {
  font-size: 13px;
}
</style>

// med_work_frontend/src/pages/Patients/components/ReportExportModal.tsx
import { useEffect, useState } from 'react';
import { App as AntApp, DatePicker, Modal, Segmented, Select, Space, Typography } from 'antd';
import type { Dayjs } from 'dayjs';
import { downloadPatientReport } from '@/services/patients';
import type { PatientReportRange, ReportFormat } from '@/types';

const { RangePicker } = DatePicker;

/** 可选患者（列表页传勾选行，详情页传当前患者） */
export interface ReportCandidate {
  id: number;
  name: string;
  patient_no: string;
}

interface ReportExportModalProps {
  open: boolean;
  candidates: ReportCandidate[];
  /** 打开时预选中的患者 ID */
  defaultIds?: number[];
  /** 锁定选择（详情页导出当前患者时无需再选） */
  lockSelection?: boolean;
  onClose: () => void;
}

/**
 * 导出患者诊疗分析报告（Word）。
 * 支持多选患者（逐个下载）与可选时间范围（留空导出全部记录）。
 */
export default function ReportExportModal({
  open,
  candidates,
  defaultIds,
  lockSelection = false,
  onClose,
}: ReportExportModalProps) {
  const { message } = AntApp.useApp();
  const [ids, setIds] = useState<number[]>([]);
  const [range, setRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [format, setFormat] = useState<ReportFormat>('docx');
  const [submitting, setSubmitting] = useState(false);

  const defaultKey = (defaultIds ?? []).join(',');
  useEffect(() => {
    if (!open) return;
    setIds(defaultKey ? defaultKey.split(',').map(Number) : []);
    setRange(null);
    setFormat('docx');
  }, [open, defaultKey]);

  const handleOk = async () => {
    if (!ids.length) {
      message.warning('请选择要导出的患者');
      return;
    }
    setSubmitting(true);
    try {
      const payload: PatientReportRange = {
        start_date: range?.[0]?.format('YYYY-MM-DD'),
        end_date: range?.[1]?.format('YYYY-MM-DD'),
      };
      for (const id of ids) {
        // 逐个 await：避免并发触发浏览器的多文件下载拦截
        await downloadPatientReport(id, payload, format);
      }
      message.success(ids.length > 1 ? `已导出 ${ids.length} 份报告` : '报告已开始下载');
      onClose();
    } catch (error) {
      message.error(error instanceof Error ? error.message : '导出失败');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Modal
      title="导出患者诊疗分析报告"
      open={open}
      onOk={handleOk}
      confirmLoading={submitting}
      onCancel={onClose}
      okText={format === 'pdf' ? '导出 PDF' : '导出 Word'}
      cancelText="取消"
      destroyOnHidden
      width={480}
    >
      <Space direction="vertical" size={16} style={{ width: '100%', marginTop: 12 }}>
        <div>
          <div style={{ fontSize: 13, marginBottom: 6 }}>导出格式</div>
          <Segmented
            block
            value={format}
            onChange={(value) => setFormat(value as ReportFormat)}
            options={[
              { value: 'docx', label: 'Word（可编辑再打印）' },
              { value: 'pdf', label: 'PDF（版式固定）' },
            ]}
          />
        </div>
        <div>
          <div style={{ fontSize: 13, marginBottom: 6 }}>选择患者{lockSelection ? '' : '（可多选）'}</div>
          <Select
            style={{ width: '100%' }}
            placeholder="请选择患者"
            disabled={lockSelection}
            showSearch
            optionFilterProp="label"
            mode={lockSelection ? undefined : 'multiple'}
            value={lockSelection ? ids[0] : ids}
            onChange={(value) => setIds(lockSelection ? [value as number] : (value as number[]))}
            options={candidates.map((item) => ({
              value: item.id,
              label: `${item.name}　${item.patient_no}`,
            }))}
          />
        </div>

        <div>
          <div style={{ fontSize: 13, marginBottom: 6 }}>时间范围（可选）</div>
          <RangePicker
            style={{ width: '100%' }}
            value={range}
            onChange={(value) => setRange(value as [Dayjs, Dayjs] | null)}
            placeholder={['开始日期', '结束日期']}
          />
        </div>

        <Typography.Text type="secondary" style={{ fontSize: 12 }}>
          报告包含患者基本信息、所选时间范围内的全部病历记录与 AI 分析（结论 / 关注点 /
          循证依据），导出为可编辑的 Word 文档；留空时间范围表示导出全部记录。
        </Typography.Text>
      </Space>
    </Modal>
  );
}
