// med_work_admin/src/components/med/doc-overview.vue
<script lang="ts" setup>
/**
 * 文档管理「概览」视图：KPI + 文档构成 + 知识质量看板。
 * 迁移自 med-work-frontend DocOverview。
 */
import { onMounted, ref } from 'vue';

import { getKnowledgeOverviewApi } from '#/api/med/documents';
import type { KnowledgeOverview } from '#/types/med';

import KpiCard from '#/components/med/kpi-card.vue';

function formatBytes(n: number): string {
  if (!n) return '0 B';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

const loading = ref(false);
const data = ref<KnowledgeOverview | null>(null);

async function load() {
  loading.value = true;
  try {
    data.value = await getKnowledgeOverviewApi();
  } finally {
    loading.value = false;
  }
}

onMounted(load);

const total = () => data.value?.total_documents ?? 0;
const ready = () => data.value?.ready_documents ?? 0;
const parsing = () => data.value?.parsing_documents ?? 0;
const failed = () => data.value?.failed_documents ?? 0;
const totalSize = () => data.value?.total_size_bytes ?? 0;
const totalChunks = () => data.value?.total_chunks ?? 0;
const totalVectors = () => data.value?.total_vectors ?? 0;

const indexRatio = () => {
  const t = total();
  if (t === 0) return 0;
  return Math.round((ready() / t) * 1000) / 10;
};

const typeTotal = () =>
  (data.value?.doc_type_distribution ?? []).reduce(
    (sum, d) => sum + d.count,
    0,
  );

const typeRows = () => {
  const t = typeTotal();
  return (data.value?.doc_type_distribution ?? []).map((d) => ({
    ...d,
    ratio: t > 0 ? Math.round((d.count / t) * 1000) / 10 : 0,
  }));
};

const qualityRows = () => {
  const t = total();
  return [
    {
      color: '#722ed1',
      label: '向量索引覆盖率',
      ratio: indexRatio(),
      value: `${indexRatio()}%`,
    },
    {
      color: '#fa8c16',
      label: '处理中文档',
      ratio: t > 0 ? Math.round((parsing() / t) * 1000) / 10 : 0,
      value: `${parsing()} 篇`,
    },
    {
      color: '#f5222d',
      label: '索引失败文档',
      ratio: t > 0 ? Math.round((failed() / t) * 1000) / 10 : 0,
      value: `${failed()} 篇`,
    },
  ];
};
</script>

<template>
  <div v-loading="loading" class="med-doc-overview">
    <div class="med-kpi-grid">
      <KpiCard
        label="文档总数"
        icon="docs"
        icon-color="blue"
        :value="String(total())"
        unit="篇"
        :desc="`占用 ${formatBytes(totalSize())}`"
      />
      <KpiCard
        label="已索引"
        icon="valid"
        icon-color="green"
        :value="String(ready())"
        unit="篇"
        :desc="`索引覆盖率 ${indexRatio()}%`"
      />
      <KpiCard
        label="处理中"
        icon="update"
        icon-color="orange"
        :value="String(parsing())"
        unit="篇"
        desc="等待向量化完成"
      />
      <KpiCard
        label="索引失败"
        icon="review"
        icon-color="purple"
        :value="String(failed())"
        unit="篇"
        desc="需检查后重试"
      />
    </div>

    <div class="med-doc-grid">
      <el-card shadow="never" class="med-doc-card">
        <template #header>
          <div class="med-doc-card-head">
            <span>文档构成</span>
            <span class="med-doc-sub">各类型文档占比</span>
          </div>
        </template>
        <div class="med-doc-card-body">
          <template v-if="typeRows().length">
            <div
              v-for="row in typeRows()"
              :key="row.doc_type"
              class="med-doc-bar"
            >
              <div class="med-doc-bar-row">
                <span class="med-doc-bar-label">{{ row.label }}</span>
                <strong>
                  {{ row.count }} 篇
                  <span class="med-doc-bar-ratio">· {{ row.ratio }}%</span>
                </strong>
              </div>
              <el-progress
                :percentage="row.ratio"
                :show-text="false"
                :stroke-width="6"
                :color="[
                  { color: '#1677ff', percentage: 50 },
                  { color: '#722ed1', percentage: 100 },
                ]"
              />
            </div>
          </template>
          <el-empty
            v-else
            description="暂无文档，可在「本地知识库」中上传"
            :image-size="80"
          />
          <div class="med-doc-summary">
            索引规模：<strong>{{ total() }} 篇</strong> · 文本分块
            <strong>{{ totalChunks() }}</strong> · 向量
            <strong>{{ totalVectors() }}</strong>
          </div>
        </div>
      </el-card>

      <el-card shadow="never" class="med-doc-card">
        <template #header>
          <div class="med-doc-card-head">
            <span>知识质量看板</span>
            <span class="med-doc-sub">知识库健康度指标</span>
            <el-tag
              :type="indexRatio() === 100 ? 'success' : indexRatio() > 0 ? 'primary' : 'warning'"
              size="small"
            >
              {{ indexRatio() }}% 已索引
            </el-tag>
          </div>
        </template>
        <div class="med-doc-card-body">
          <div
            v-for="q in qualityRows()"
            :key="q.label"
            class="med-doc-bar"
          >
            <div class="med-doc-bar-row">
              <span class="med-doc-bar-label">{{ q.label }}</span>
              <strong>{{ q.value }}</strong>
            </div>
            <el-progress
              :percentage="q.ratio"
              :show-text="false"
              :stroke-width="6"
              :color="q.color"
            />
          </div>
        </div>
      </el-card>
    </div>
  </div>
</template>

<style scoped>
.med-doc-overview {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.med-kpi-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px;
}

.med-doc-grid {
  display: grid;
  grid-template-columns: 1fr 1.4fr;
  gap: 12px;
}

@media (width <= 1100px) {
  .med-doc-grid {
    grid-template-columns: 1fr;
  }
}

.med-doc-card :deep(.el-card__body) {
  padding: 16px 20px;
}

.med-doc-card-head {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
  font-size: 14px;
}

.med-doc-sub {
  color: var(--el-text-color-secondary);
  font-size: 12px;
  font-weight: 400;
}

.med-doc-card-head .el-tag {
  margin-left: auto;
}

.med-doc-card-body {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.med-doc-bar {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.med-doc-bar-row {
  display: flex;
  justify-content: space-between;
  font-size: 12.5px;
  color: var(--el-text-color-primary);
}

.med-doc-bar-label {
  color: var(--el-text-color-secondary);
}

.med-doc-bar-ratio {
  color: var(--el-text-color-secondary);
  font-weight: 400;
}

.med-doc-summary {
  margin-top: auto;
  padding: 12px;
  background: var(--el-fill-color-light);
  border-radius: 8px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
</style>

// med_work_frontend/src/pages/Documents/components/DocOverview.tsx
import { useEffect } from 'react';
import { Card, Empty, Flex, Progress, Tag, Typography } from 'antd';
import { KpiCard } from '@/components';
import { colors } from '@/theme';
import { useKnowledgeStore } from '@/stores/knowledge';

/** 卡片头：标题 + 副标题（antd 组合） */
function CardHead({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <Flex vertical gap={3}>
      <Typography.Text strong style={{ fontSize: 15 }}>
        {title}
      </Typography.Text>
      <Typography.Text type="secondary" style={{ fontSize: 12 }}>
        {subtitle}
      </Typography.Text>
    </Flex>
  );
}

function formatBytes(n: number): string {
  if (!n) return '0 B';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

/** 文档管理「概览」：KPI + 文档构成 + 知识质量看板（知识库总览并入文档管理） */
export default function DocOverview() {
  const { overview, loadOverview } = useKnowledgeStore();

  useEffect(() => {
    void loadOverview();
  }, [loadOverview]);

  const o = overview;
  const totalDocs = o?.total_documents ?? 0;
  const ratio = totalDocs > 0 ? Math.round(((o?.ready_documents ?? 0) / totalDocs) * 1000) / 10 : 0;
  const typeTotal = o?.doc_type_distribution?.reduce((s, d) => s + d.count, 0) ?? 0;

  const kpis = [
    {
      label: '文档总数',
      value: String(totalDocs),
      unit: '篇',
      desc: `占用 ${formatBytes(o?.total_size_bytes ?? 0)}`,
      icon: 'docs',
      iconColor: 'blue',
    },
    {
      label: '已索引',
      value: String(o?.ready_documents ?? 0),
      unit: '篇',
      desc: `索引覆盖率 ${ratio}%`,
      icon: 'valid',
      iconColor: 'green',
    },
    {
      label: '处理中',
      value: String(o?.parsing_documents ?? 0),
      unit: '篇',
      desc: '等待向量化完成',
      icon: 'update',
      iconColor: 'orange',
    },
    {
      label: '索引失败',
      value: String(o?.failed_documents ?? 0),
      unit: '篇',
      desc: '需检查后重试',
      icon: 'review',
      iconColor: 'purple',
    },
  ];

  return (
    <>
      <div className="kpi-grid">
        {kpis.map((k) => (
          <KpiCard key={k.label} {...k} />
        ))}
      </div>

      <div className="grid-2" style={{ gridTemplateColumns: '1fr 1.4fr' }}>
        {/* 文档构成 */}
        <Card
          title={<CardHead title="文档构成" subtitle="各类型文档占比" />}
          styles={{ body: { padding: '16px 20px', display: 'flex', flexDirection: 'column', gap: 18, flex: 1, minHeight: 0 } }}
        >
          {(o?.doc_type_distribution ?? []).map((d) => {
            const p = typeTotal > 0 ? Math.round((d.count / typeTotal) * 1000) / 10 : 0;
            return (
              <div key={d.doc_type}>
                <div
                  style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 6 }}
                >
                  <span className="text-secondary">{d.label}</span>
                  <strong>
                    {d.count} 篇 <span className="text-muted" style={{ fontWeight: 400 }}>· {p}%</span>
                  </strong>
                </div>
                <Progress
                  percent={p}
                  showInfo={false}
                  strokeColor={{ '0%': colors.primary, '100%': colors.ai }}
                  railColor="#EEF1F6"
                  size="small"
                />
              </div>
            );
          })}
          {(o?.doc_type_distribution ?? []).length === 0 && (
            <Empty
              image={Empty.PRESENTED_IMAGE_SIMPLE}
              description="暂无文档，可在「本地知识库」中上传"
            />
          )}
          <div
            style={{
              marginTop: 'auto',
              padding: 12,
              background: colors.bgSecondary,
              borderRadius: 8,
              fontSize: 12,
              color: colors.textMuted,
            }}
          >
            索引规模：<strong className="text-secondary">{totalDocs} 篇</strong> · 文本分块{' '}
            <strong className="text-secondary">{o?.total_chunks ?? 0}</strong> · 向量{' '}
            <strong className="text-secondary">{o?.total_vectors ?? 0}</strong>
          </div>
        </Card>

        {/* 知识质量看板 */}
        <Card
          title={<CardHead title="知识质量看板" subtitle="知识库健康度指标" />}
          extra={
            <Tag
              color={ratio === 100 ? 'success' : ratio > 0 ? 'blue' : 'warning'}
              style={{ marginRight: 0 }}
            >
              {ratio}% 已索引
            </Tag>
          }
          styles={{ body: { padding: '16px 20px', display: 'flex', flexDirection: 'column', gap: 14, flex: 1, minHeight: 0 } }}
        >
          {[
            {
              label: '向量索引覆盖率',
              value: `${ratio}%`,
              ratio,
              color: 'ai',
            },
            {
              label: '处理中文档',
              value: `${o?.parsing_documents ?? 0} 篇`,
              ratio: totalDocs > 0 ? Math.round(((o?.parsing_documents ?? 0) / totalDocs) * 1000) / 10 : 0,
              color: 'warning',
            },
            {
              label: '索引失败文档',
              value: `${o?.failed_documents ?? 0} 篇`,
              ratio: totalDocs > 0 ? Math.round(((o?.failed_documents ?? 0) / totalDocs) * 1000) / 10 : 0,
              color: 'error',
            },
          ].map((q) => (
            <div key={q.label}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12, marginBottom: 6 }}>
                <span className="text-secondary">{q.label}</span>
                <strong>{q.value}</strong>
              </div>
              <Progress
                percent={q.ratio}
                showInfo={false}
                strokeColor={q.color === 'ai' ? colors.ai : q.color === 'error' ? colors.error : colors.warning}
                railColor="#EEF1F6"
                size="small"
              />
            </div>
          ))}
        </Card>
      </div>
    </>
  );
}
