// med_work_admin/src/components/med/status-tag.vue
<script lang="ts" setup>
/**
 * 业务状态/类型/置信度标签（迁移自 med-work-frontend StatusTag）
 */
import { computed } from 'vue';

import { STATUS_MAP } from '#/constants/med';
import type { StatusKey } from '#/types/med';

const props = defineProps<{
  /** 状态键（review/running/done/failed/pending/in/out） */
  status: StatusKey;
}>();

/** 自定义 tag 类名 → Element Plus tag 类型 + 自定义色 */
const CLS_TO_TAG: Record<string, { color?: string; type: string }> = {
  'tag-success': { type: 'success' },
  'tag-warning': { type: 'warning' },
  'tag-error': { type: 'danger' },
  'tag-info': { type: 'primary' },
  'tag-ai': { color: '#722ed1', type: 'primary' },
  'tag-primary': { type: 'primary' },
  'tag-purple': { color: '#722ed1', type: 'primary' },
  'tag-neutral': { type: 'info' },
};

const meta = computed(() => {
  const s = STATUS_MAP[props.status] ?? STATUS_MAP.pending!;
  return CLS_TO_TAG[s.cls] ?? CLS_TO_TAG['tag-neutral']!;
});

const text = computed(() => {
  const s = STATUS_MAP[props.status] ?? STATUS_MAP.pending!;
  return s.text;
});

const tagStyle = computed(() =>
  meta.value.color
    ? {
        '--el-tag-bg-color': '#f9f0ff',
        '--el-tag-border-color': '#d3adf7',
        '--el-tag-text-color': meta.value.color,
      }
    : undefined,
);
</script>

<template>
  <el-tag :style="tagStyle" :type="meta.type" disable-transitions>
    {{ text }}
  </el-tag>
</template>

// med_work_frontend/src/components/StatusTag/index.tsx
import { Tag } from 'antd';
import { STATUS_MAP, TYPE_CLS_MAP, CONFIDENCE_THRESHOLD } from '@/constants';
import type { StatusKey } from '@/types';

export type { StatusKey };

/** 自定义 tag 类名 → antd preset 颜色 */
const CLS_TO_COLOR: Record<string, string> = {
  'tag-success': 'success',
  'tag-warning': 'warning',
  'tag-error': 'error',
  'tag-info': 'blue',
  'tag-ai': 'purple',
  'tag-primary': 'blue',
  'tag-purple': 'purple',
  'tag-neutral': 'default',
};

function toColor(cls: string): string {
  return CLS_TO_COLOR[cls] ?? 'default';
}

/** 业务状态标签 */
export default function StatusTag({ status }: { status: StatusKey }) {
  const s = STATUS_MAP[status] ?? STATUS_MAP.pending;
  return (
    <Tag color={toColor(s.cls)} style={{ marginInlineEnd: 0 }}>
      {s.text}
    </Tag>
  );
}

/** 状态标签（别名，兼容历史引用） */
export function StatusBadge({ status }: { status: StatusKey }) {
  return <StatusTag status={status} />;
}

/** 业务类型标签 */
export function TypeTag({ type }: { type: string }) {
  return (
    <Tag color={toColor(TYPE_CLS_MAP[type] ?? 'tag-neutral')} style={{ marginInlineEnd: 0 }}>
      {type}
    </Tag>
  );
}

/** 置信度标签 */
export function ConfidenceCell({ value }: { value: number }) {
  const cls =
    value >= CONFIDENCE_THRESHOLD.high
      ? 'tag-success'
      : value >= CONFIDENCE_THRESHOLD.medium
        ? 'tag-info'
        : 'tag-warning';
  return (
    <Tag color={toColor(cls)} style={{ marginInlineEnd: 0 }}>
      {value}%
    </Tag>
  );
}
